### ISSUE TITLE
Проблем со текстот во новости! 

### ISSUE THREAD

**Issue by Pipelin** [skechboy/MAFIA#1]
ÐžÑÐ½Ð¾Ð²Ð°ÑšÐµ Ð½Ð° Ñ„Ð°Ð¼Ð¸Ð»Ð¸Ñ˜Ð°  

http://pipelin.ws.mk/files/novosti.png 

Проблеми со кирилицата.

**Comment by skechboy** [comment]
Проблемот е решен ти благодарам за известувањето.
