### ISSUE TITLE
Графички измени

### ISSUE THREAD

**Issue by extremebt** [skechboy/MAFIA#10]
Да се стават новите слики за дрога, новите слики за коли (со бели таблици), текст под сликата со награди, кафеавите квадратчиња (долу најлево и најдесно) шо се? :)

**Comment by skechboy** [comment]
Средено, иако некако сликите со колите ми изгледаат некако шторо поради таблиците можеби најдобро би било да пишува на нив само MAFIA за да не правиме за секоја локална верзија различни слики :)

**Comment by DeadBoss** [comment]
Баш личат со таблици како реални автомобили --> мое мислење ! :D
