### ISSUE TITLE
Кредити

### ISSUE THREAD

**Issue by JasSumToj** [skechboy/MAFIA#102]

**Comment by JasSumToj** [comment]
Za sto sluzat kreditite moze nekoj da mi kazE?

**Comment by hvardovski** [comment]
И јас исто така прашувам

**Comment by Lart** [comment]
Сигурно би биле за купување на ВИП работи..

**Comment by kuche** [comment]
jas mislam ... ako te ubijat 5 pati ... da si go vratis profilot so plakjanje na krediti ;)

**Comment by hvardovski** [comment]
А може и да си купуваш пвеќе животи.
