### ISSUE TITLE
Pari i Pocit

### ISSUE THREAD

**Issue by JasSumToj** [skechboy/MAFIA#103]
na pr. eden igrac  da moze da praka pari,mok..na pr.koga ke vlezis na nekoj profil da ima :
Прати моќ на играчот,
Прати пари на играчот.
So toa bi mu pomognale na nekoj vas prijatel ili pak nekoj moze za vistinski pari da kupi mok od drug igrac.

**Comment by skechboy** [comment]
Предлогот е добар, но секако многу играчи ова ќе го злоупотребат.

**Comment by Lart** [comment]
Добро е за пари давање, но за моќ не се согласувам
