### ISSUE TITLE
Патување

### ISSUE THREAD

**Issue by JasSumToj** [skechboy/MAFIA#104]
Би било поубаво ако со :
Воз - да можеш да патуваш само во државата !
Автобус - во државата и надвор од неа т.е и во други држави !
Авион - да можеш да патуваш само надвор од државата т.е само во други Држави !!!

**Comment by hvardovski** [comment]
Да добро е но сите ке патуваат со авобус

**Comment by Lart** [comment]
Да сите со автобус ке одат
