### ISSUE TITLE
Тајниот Линк

### ISSUE THREAD

**Issue by Cool4life** [skechboy/MAFIA#105]
Ми се чини дека кога некој ќе го посети твојот таен линк не добиваш 500 евра во кеш, ниту 1000 евра во банка

**Comment by dare32** [comment]
Ако некој го посети твојот таен линк ти добиваш еден платен убиец, 100 € кеш и 500 € на твојата банкарска сметка! 
Стигнува ..!

**Comment by Cool4life** [comment]
Е како стигнува вчера 50 души ми го посетија ни скршен денар не добив
