### ISSUE TITLE
ПРЕДЛОГ

### ISSUE THREAD

**Issue by kikec2000** [skechboy/MAFIA#106]
ЈАС ПРЕДЛОЖУВАМ ДА СЕ НАПРАВИ МАФИА.МК ПРОФИЛ И НА НЕГО ДА СЕ ПУШТААТ СИТЕ МАФИАШИ И САМИ НА ДР. ПРОФИЛИ ДА СИ СТИСКААТ ТАЕН ЛИНК И ДА ИГРААТ НА ТОЈ ПРОФИЛ И ДА АДМИНИТЕ ДА ГЛЕДААТ КОЈ СЕ ПУШТА НАЈВЕЌЕ!

**Comment by Lart** [comment]
Објасни појасно, нишо не те сфатив!

**Comment by kikec2000** [comment]
zaednicki mafia.mk profil !

**Comment by Lart** [comment]
Не е баш добар предлогот

**Comment by lion4e** [comment]
i ne e razbirliv...
