### ISSUE TITLE
Novi Sad mi go nema na listata.

### ISSUE THREAD

**Issue by Krichi** [skechboy/MAFIA#112]
Novi Sad go nema na listata na patuvanje. Ako ne se lazam toa e vo Srbija i sea koga otvoram da patuvam go ima samo Blegrad i Nish. Ni vo drugi drzavi go nema. Ova da ne e bug ili neshto drugo neznam.

**Comment by Lart** [comment]
Не, само со авион можиш да патуваш во Ниш и во Белград оти само тие градови во Србија имат аеродром, кога ке стигнеш во Белград или Ниш, од таму ке можеш да патуваш во Нови Сад!
