### ISSUE TITLE
Автомобилски Трки - Предлог

### ISSUE THREAD

**Issue by Lart** [skechboy/MAFIA#114]
1 од 20 пати ке победам во трка, еднаш ке ме фати полиција, еднаш ке изгубам, еднаш случајот со детенцето, многу е мала шансата за да победиш и не е фер, кога е така сите само ке си ја продаваат колата и ке нема автомобилски трки. Ве молам или избришете или зголемета ја шансата за победување на трки!

Фала унапред

**Comment by skechboy** [comment]
Шансата за победа во автомобилските трки ти се зголемува доколку се тркаш со побрзи и помоќни автомобили.

**Comment by Lart** [comment]
А може па да пишува колку е шансата за победа за секој Автомобил
