### ISSUE TITLE
Мисија: Изврши тешко злосторство не работи

### ISSUE THREAD

**Issue by Nexus123** [skechboy/MAFIA#115]
Три пати ја имам извршено мисијата изврши тешко злосторство и не ми кажува дека е извршена :S

**Comment by Hellmafiamk** [comment]
да да и ја приметив

**Comment by DamDav159** [comment]
да и јас приметив

**Comment by skechboy** [comment]
Имавме грешка во описот на мисијата :) За повеќе информации проверете во http://www.mafia.mk/missions
