### ISSUE TITLE
Изместена сликата кај Болница

### ISSUE THREAD

**Issue by klikstermkd** [skechboy/MAFIA#12]
Сликата кај Болница е изместена. Овој проблем се јавува само на Firefox додека на Chrome е во ред.

http://pic.mk/images/bolnica.jpg

**Comment by Pipelin** [comment]
Кај мене е океј пробај со CTRL + 0 дали ќе се реши

**Comment by Pipelin** [comment]
Ова се случува кога си на 100% Здравје сега и кај мене се појави.

**Comment by klikstermkd** [comment]
@Pipelin дали кај тебе 100% се гледа целосно или тоа % е малце скратено?

**Comment by Pipelin** [comment]
Скратено е и можеш да го селектираш и со глувчето надесно ако отидеш ќе се прикаже цело :)

**Comment by klikstermkd** [comment]
Да да и кај мене е така се надевам дека админите ќе го средат овој проблем :)

**Comment by skechboy** [comment]
И админите го решија и овој проблем :) :) Ви благодарам за известувањето дечки.
