### ISSUE TITLE
Голема грешка кај градовите

### ISSUE THREAD

**Issue by Pipelin** [skechboy/MAFIA#120]
И покрај тоа што нема играчот сателит и вселенска станица, откако ќе го отвори профил од друг играч ќе му се појави градот доколку се доближи до неговиот ник. 
Ова според мене е малце сериозен bug кој треба да се поправи. 

Еве слика како изгледа: http://pipelin.ws.mk/files/bagtop1.png

**Comment by krstep** [comment]
Confirmed.

**Comment by klikstermkd** [comment]
Не мора само на профил, било каде (почетна, кај листата на играчи...) да се доближи до неговиот ник ќе го кажи градот.

**Comment by hvardovski** [comment]
Не е така фер спрема тие со имаат сателити.

**Comment by skechboy** [comment]
Грешката е одстранета ви благодарам за известувањето.
