### ISSUE TITLE
Проблем со листата на убиени мафијаши

### ISSUE THREAD

**Issue by Pipelin** [skechboy/MAFIA#121]
Во листата на убиени мафијаши има играчи кои се убиени, и истите никот не им е пречкртан како на сликава: http://pipelin.ws.mk/files/mafiabag2.png  и истите сеуште се мртви. И исто така кога ќе му отворам профил се појавува порака тој и тој е убиен и во позадина силата му е 22% :) (малце смешно, Слика: http://pic.mk/images/untitl1292801341.png )

Не сум сигурен, не забележав, но доколку истиот играч кој нему е пречкртан никот е активен мислам дека и во активни мафијаши ќе биде истото...

**Comment by skechboy** [comment]
Проблемот е решен ти благодарам за известувањето.
