### ISSUE TITLE
ГРЕШКИ -МИСИИ

### ISSUE THREAD

**Issue by kuche** [skechboy/MAFIA#122]
Имам 2 грешки ...
*1ва.Имам гласено за поддршка на МАФИА.МК не ми покажува дека сум ја завршил мисијата успешно.
*2ра.Имам извршено тешко злосторство околу 500 пати успеав и пак не ми дава дека сум ја извршил мисијата успешно.

**Comment by Krichi** [comment]
1ва.Имам гласено за поддршка на МАФИА.МК не ми покажува дека сум ја завршил мисијата успешно.
I mene ne mi raboti taa misija.

**Comment by hvardovski** [comment]
Се извршива успешно првата мисија еве слика:http://www.pic.mk/images/untitl1292864011.
