### ISSUE TITLE
Kako brgu da izlezesh od zatvor?

### ISSUE THREAD

**Issue by Krichi** [skechboy/MAFIA#124]
Shtom vlezesh vo zatvor klikni gore vo desniot kjosh na novi poraki i potoa na pochetna i si osloboden od zatvor. Mene taka mi se sluchi ednash.

**Comment by DisturbeD** [comment]
pa jas ti go kazav bre !!

**Comment by Pipelin** [comment]
Тоа беше еднаш кога го пријавив багот и кога се поправи :) Сега веќе неможеш да излезеш.

**Comment by skechboy** [comment]
Проблемот е одстранет. Ви благодарам за известувањето.
