### ISSUE TITLE
Грешка - брзо излегување од затвор

### ISSUE THREAD

**Issue by AsSass1N** [skechboy/MAFIA#126]
ОВА Е ОТРКИЕНО НАЈПРВО ОД DisturbeD а потоа AsSass1N

Кога не успевате да извршите злосторство или да украдете автомобли или било каков начин на кој што можете да одите во затвор кога ве известува табот тогаш ако се кликне "Пораки" потоа на "Почетна" ќе бидете на слобода или ако сте веќе во него ако кликнете на парите-Кеш исто така сте на слобода

еве видео линк :  http://www.youtube.com/watch?v=Ttv7jiEeIMY

**Comment by DisturbeD** [comment]
da greskata ke se smeta deka e najdena zaedno ...

**Comment by skechboy** [comment]
Ви благодарам за известувањето. Грешката е одстранета.

**Comment by DisturbeD** [comment]
Bi trebalo da ne nagradite :P barem po 5miliona vo licen sef da ne primeti nikoj ;P

**Comment by skechboy** [comment]
Грешката најпрво беше пријавена од Pipelin и веднаш беше исправена но со последните промени што ги правевме во играта грешката се појави повторно. Како и да е ви благодариме за пријајувањето, а за награда само продолжете вака и сигурно ќе добиете.

**Comment by DisturbeD** [comment]
hahaahhaha OKS
