### ISSUE TITLE
За продавница

### ISSUE THREAD

**Issue by Janne123** [skechboy/MAFIA#127]
Кога отидеш во продавница таб банкарство вели треба да си во град тетово .. одам патувај и македонија само скопје и охрид се го нема тетово ? bug li e sto li e ? Pisete admini

**Comment by skechboy** [comment]
Не станува збор за грешка во играта. За да стигнеш во Тетово најпрво мора да отпатуваш во Македонија преку аеродромот па потоа да отпатуваш до Тетово со автобус или воз. Кога патуваш со авион ти ги прикажува само оние градови каде што има еродром.

**Comment by Janne123** [comment]
Okay :)
