### ISSUE TITLE
Реални Цени - Предлог

### ISSUE THREAD

**Issue by Lart** [skechboy/MAFIA#128]
Како може Калаш да е 50.000$ кога тој во реално е околу 4000$??
Безбол Палка за 3000$? Паѓам во несвест!
Има некои се реални, но сеа Бело Пиштолче за 17000$

Ве молам одговорете го ова

**Comment by skechboy** [comment]
Цените се правени колку што можевме пореални, но за жал некаде цените мораа да бидат зголемени за да се одржи некаков баланс во играта.

**Comment by Pipelin** [comment]
Сепак во играта не се бара реалност. Цените се правени според целата игра, тогаш реално би требало да заработуваш по 5-10 евра. Затоа е така направено.

**Comment by Kradec** [comment]
HAHAHAHAHAHHAAHHAHA  OVAA VERZIJA E POTESKA NE E MN LESNA KAKO MAFIA BETA ! NORMALNO KE POSKAPAT I CENITE AKO E POTESKA :D:D:D No NE DO TOLKU KAKO STO E VO MOMENTOT :D:D:D bi Trebalo Da se namali Ako ne poveke barem za 5 000 :D :P

**Comment by Lart** [comment]
Па тогаш и колите нека се поскапи
