### ISSUE TITLE
ADMIN ZS NEMOZAM DA SE OSLOBODAM OD ZATVOR

### ISSUE THREAD

**Issue by Kradec** [skechboy/MAFIA#129]
кога ќе ме фанат во затвор на секоја секунда треба да се намалува цената, кај мене тоа го нема, и исто така кликам да се ослободам ! требаше да платам 5600 а јас имав во 
ќеш 8300! и пишува таму дека наскоро ќе ме ослободиле поради доброто однесување! и неможам да ја извршам мисиата бидејќи немозам да се ослободам :D зашо вака бе?

**Comment by KP3T3H** [comment]
за мисијата да ја завршиш треба да си осуден на подогло, незнам на колку време минимум треба да е за да можеш да се ослободиш.

а тоа што си бил добар во затворот, честито :)

**Comment by Kradec** [comment]
:D::DD:D
