### ISSUE TITLE
Грешка на редиректирање кај автомобили, злосторства и затвор

### ISSUE THREAD

**Issue by klikstermkd** [skechboy/MAFIA#13]
Кај автомобили доколку направиш некоја кражба, наместо да редиректира повторно на автомобили, редиректира на почетна. Истото е и кај злосторства а кај затвор откога ќе помини времето во затвор.

**Comment by skechboy** [comment]
Ова би го нарекол намерна грешка. Поради тоа што после извршувањето на злосторството нема потреба да бидеш пренасочен кон злосторства затоа што ќе ти биде испишана порака дека полицијата те бара :) се решивме да го смениме пренасочувањето со кое што заштедуваме и на серверски ресурси т.е. 1 импресија помалце :)
