### ISSUE TITLE
HITNO!!!

### ISSUE THREAD

**Issue by Kradec** [skechboy/MAFIA#130]
admin so e ova KOGA SAKAM DA NAPADNAM EDEN IGRAC MI PISUVA 

```
    GRESKA!!!!
```

 NEMOZES DA GO NAPAGAS IGRACOT
SLU4AJOT KE BIDE PRIJAVEN KAJ AMINISTRATORITE!!!!!!!

   AJ RESETE GO OVA SO POBRZO! OK?

**Comment by NEWBOY** [comment]
хахахах доколку користиш мулти акаунт и си го уклучувал тој акаунт од твојта IP адреса тогаш нормално дека нема да може :)

**Comment by dare32** [comment]
pa normalno deka nemozes koa 2ta igraci se tvoj ili se pustas na 2ta od kvoj pc !

**Comment by Lart** [comment]
Добар обид! Не се админите глупи, глуп еден

**Comment by Kradec** [comment]
ne be togas dojde drugar mi logirase na mojo komp i sea nemozam da go napagam

**Comment by Kradec** [comment]
;

**Comment by Pipelin** [comment]
А зашто да го напаѓаш другар ти :)) хехе другари, пријатели, братучеди :) и од 7 илјади играчи нив ги напаѓаме :)

**Comment by Kradec** [comment]
oti me iznervira!

**Comment by NEWBOY** [comment]
xaxax :D

**Comment by Hariss** [comment]
Абе  се интелектуалци тука Крадец од лага у лага паѓаш

**Comment by Kradec** [comment]
?
