### ISSUE TITLE
Кафетерија - Предлог

### ISSUE THREAD

**Issue by Lart** [skechboy/MAFIA#131]
Кафетеријата мислам дека дава многу малку пари на час. Тоа е само како еден да ти клика на тајниот линк секој час. Само 500? Добро ке имаш 5 кафетерии и ке земаш 2.500..ама ако платиш 1.250.000 за 5 кафетерии, има мноогу долг период додека си ги вратиш парите назад само со 2.500 на час. 

Нека биди кафетеријата барем по 1.500 на час. Одговорете
Фала унапред

**Comment by KP3T3H** [comment]
колку што се сеќавам и на бетата даваше исто, што има тука лошо.?!

**Comment by LjubeGVG** [comment]
na betata bea zlostorstavata poskapi a robotite poevtini a vo ovaa e obratno zatoa jas prifakam no neka bide 1000 od edna na cas

**Comment by hvardovski** [comment]
Da se soglasuvam i drogata e za 10 pati poskapa za nadgraduvanje
MN e skapo

**Comment by shadowrider1** [comment]
kako se dobiva pari od kafeterijata vo kes ti gi davaat na cas ili vo banka??

**Comment by KP3T3H** [comment]
parite od kafeterijata idat vo obicna banka

**Comment by xBOJANx** [comment]
slozuvam se so predlogot

**Comment by shadowrider1** [comment]
i jas se slozuvam!! vistina barem po 1000- 1500 na cas a ne vaka 500!

**Comment by skechboy** [comment]
Една кафитерија чини 250.000 € а истата дава по 500 € на час што значи во ден добивате по 12.000 € што и не е баш малце ако земеме во предвид дека после 20 дена парите што ќе ви доаѓаат на сметката ќе бидат чист профит.

Жалам што ќе ве разочарам но профитот си оставува ист :) Поздрав
