### ISSUE TITLE
Предлог - Форум

### ISSUE THREAD

**Issue by Lart** [skechboy/MAFIA#132]
Да има форум ке биде најдобро, наместо да прашуваат глупи прашања овие што незнаат да играат (без навреда). Во форумот ке има и многу други разни работи. Ако може да се направи еден, ке бидам благодарен.

Фала

**Comment by KP3T3H** [comment]
имаше форум, незнам кај отиде.....

**Comment by Pipelin** [comment]
Ќе дојде кај и да е после нова година :)
