### ISSUE TITLE
Грешка - Без сателит се гледа каде се другите

### ISSUE THREAD

**Issue by Lart** [skechboy/MAFIA#134]
И да немаш ни сателит, ни вселенска станица, пак можеш да гледаш каде се другите ако влезиш во Будни мафијаши и само со маусо поминуваш на нивните имиња и ти кажува во кој град е. Неможи да се објасни со скриншо, проверете сами и ке се уверите.

Поправете го ова оти не е фер за некои кои дадоа пари за Сателит и Вселенската.

Фала

**Comment by KP3T3H** [comment]
поправено е, и плус веќе имаше ваква тема

**Comment by Hellmafiamk** [comment]
не е поправено сеа видов!!

**Comment by skechboy** [comment]
Hellmafiamk проблемот е решен пред неколку дена. Би било супер да прикажеш некој пример поздрав.
