### ISSUE TITLE
има грешка кај продавницата 

### ISSUE THREAD

**Issue by dragan0041** [skechboy/MAFIA#135]
пишува во градот тетово а градот тетово го нема во патувај исто и со нови сад ве молам поправете го тоа не можеме да дигаме моќ

**Comment by kuche** [comment]
pa vo sekoj grad nema ... aerodrom be treba da odpatuvas vo drug grad kade go ima aerodromot...pa posle tetovo

**Comment by KP3T3H** [comment]
многу пари се трошат така, нека направат сите тие продавници (за оружје, шпиунирање, банкарство итн) да бидат во градови каде што има аеродром, вака не иде...

**Comment by DiChOoO** [comment]
Vo Tetovo nema aerodrom i ne ti go pokazhuva.. Treba prven da otidesh so avion vo nekoj grad vo Makedonija (Skopje ili Ohrid) Pa posle toa so avtobus ili voz za da stignesh do Tetovo..

**Comment by lion4e** [comment]
to4no DiChOoO... a i smislata na ovaa sezona na mafia.mk e so pomalce pari da se igra... a ne kako na beta.mafia.mk 78958945758345890 miljardi.... :)) samo so poenite e preterrano... 1 poen 5000 evra... :S

**Comment by kuche** [comment]
lol so pomalce pari vika na novava? aj kje viish igraj dolgo vreme kje viish na krajot kje prskaat parite

**Comment by dragan0041** [comment]
vi blagodaram :D :D
