### ISSUE TITLE
?

### ISSUE THREAD

**Issue by DamDav159** [skechboy/MAFIA#136]
Јас оваа страница http://mafiaprenesuvac.tk/ ја задов од овој играч http://www.mafia.mk/profile/7572 dimitar39.Сакам да знам дали оваа страница е легална или некој хак.Чекам одговор.

сраницата: http://mafiaprenesuvac.tk/

**Comment by klikstermkd** [comment]
Ова е фишинг страница, значи не е никако поврзана со играта и служи само за злоупотреба на играчите.

**Comment by DamDav159** [comment]
ok
