### ISSUE TITLE
Додавањето на пријатели не работи

### ISSUE THREAD

**Issue by klikstermkd** [skechboy/MAFIA#14]
Додавањето на пријатели не работи. Од кога ќе кликнеш кај некој профил на линкот "Пријателство" само те носи во "Пријатели" и ништо не се случува.

**Comment by lion4e** [comment]
da.... i jas isto nemozam da dodadam prijatel....

**Comment by hvardovski** [comment]
I jas isto

**Comment by skechboy** [comment]
Запознаени сме со проблемот работиме на негово решавање. Ви благодариме за известувањето.

**Comment by ace66** [comment]
isto taka ne raboti i toa koga ke ukradam kola mi ja nema vo garaza zosto nekoj znae li ???

**Comment by Pipelin** [comment]
Како може да ти ја нема? јас крадам па не ми се случило тоа, која кола?

**Comment by ace66** [comment]
нема врска која кола досега имам 10 украдено од тие 10 само една ми ја имаше а пари ми дава со сум ги крадел

**Comment by ace66** [comment]
немозам да ги продадам колите само максималната корист ја зиам

**Comment by Pipelin** [comment]
дај слика. прикачи на Pic.mk да видиме.

**Comment by ace66** [comment]
http://pic.mk/images/untitl1292533665.

**Comment by ace66** [comment]
http://pic.mk/images/untitl1292534509. eve uverete se i sami kradam koli a mi gi nema vo garaza :@

**Comment by Pipelin** [comment]
Ти правиш злосторство и добиваш само пари.
http://www.mafia.mk/stealcars оди тука укради некоја кола и ќе ти ја има во гаража.

**Comment by darkob** [comment]
хаха

**Comment by Kradec** [comment]
uste ne e resen daj resetego

**Comment by lion4e** [comment]
hahahahaha

**Comment by LjubeGVG** [comment]
a ova so prijatelite ke go popravat adminite

**Comment by stefan96** [comment]
hahahha:D

**Comment by DarkoGit** [comment]
i kaj mene gi nema kolite vo garaza a gi kradam od linkot sto go dadovte ne e mozno ova veke :@:@:@:@

**Comment by Princesss** [comment]
i mene isto ne mi dodava prijateli

**Comment by riba** [comment]
Надевај се дека ќе го поправат хахахаха

**Comment by LjubeGVG** [comment]
vo slednata sezona moze

**Comment by lion4e** [comment]
mozhi i vo slednata sezona ke mozhime da pravime FAM. nie kumoj sho sme -.-

**Comment by Slavco16** [comment]
Abe daj neka vidi nekoj na kraj toa  sto go imam pisano i jas nemozam da dodadam prijatel ama  i koga napragjam mi vika sum sakal da se samoubijam i mi se blokiram pistolot lol xD

**Comment by Slavco16** [comment]
I lizavce 100% mi ke go ukradam vo zatvor idam Ford mondeo se krade lol xD

**Comment by ChillmaxTM** [comment]
site problemu ke se resat na 28.02.2011

**Comment by DroWRaNgeR** [comment]
kako site problemi ke se resat zosto sega uste ne raboti dodavanje na prijateli ??  ?? ??

**Comment by ChillmaxTM** [comment]
nz rekoa deka se ke se resi na 28.02.2011 ama toa trebase uste od koga da go pravat koga pocna vaa sezona togas trebase da ima se napraveno toa im e golema greska ako sakaat da ima mnogu igraci treba da gi pustat site opcii i drugi raboti za da bide interesno kolku predlozi ima duri od sega treba da ja pravat drugataa sezona treba za se da im se isplanira za se da ima vo vaa i drugata sezona.

**Comment by viktorpejkovski** [comment]
jas ne mozan misto da praam se mi pokazuva na ova da stiskam Огласувајте се паметно
Обратете и се на Вашата целна публика, огласувајте се со нас.

**Comment by shortyrider** [comment]
vistina nikako nemozam da add prijatel
