### ISSUE TITLE
Грешка !!

### ISSUE THREAD

**Issue by DisturbeD** [skechboy/MAFIA#140]
има грешка кај поените за напад:
 http://img149.imageshack.us/img149/4927/72335120.png

**Comment by DiChOoO** [comment]
Ne e toa nikakva greshka.. Koga kupuvash poeni, kupuvash po 1.. A toa tamu ti objasnuva deka treba da kupish 5 poeni za napad za da mozhesh da gi napagjash drugite mafijashi..

**Comment by DisturbeD** [comment]
ne beta ti davase po 3 na ovaa po 1 a na slednata po o.5 :D a pogledni istrel koga stasal cistac v4era bese potrcko.....hahhahahah

**Comment by klikstermkd** [comment]
Од каде си сигурен дека вчера беше поттрчко? Имаш доказ?

**Comment by DisturbeD** [comment]
go vidov vo zatvor potr4ko i sega e cistac ne se nadav deka e citer i ne napraviv slika a sega neznam ima admini neka go sledat i taka
