### ISSUE TITLE
Ne dava % koga ke izvrshish zlostorstvo... bilo koe...

### ISSUE THREAD

**Issue by lion4e** [skechboy/MAFIA#142]
Ne dava % koga ke izvrshish zlostorstvo... bilo koe...

**Comment by Hariss** [comment]
како недава Мора да дава само што споро оди 25% ,25,5%

**Comment by lion4e** [comment]
hmm.. ke 4ekam odgovor od skechot bidejki i ponatamu mislam deka ne dava...

**Comment by Hariss** [comment]
Дава мене ми дава како може тебе да не ти даде
