### ISSUE TITLE
Тркало на Среќата Некад Заебава 

### ISSUE THREAD

**Issue by Hariss** [skechboy/MAFIA#146]
1 ден Ќе го завртиш друг ден ти пишува дека веќе си го завртел 
Предлог Да може да се гледаат убиствата  кој колку убиства има и така а не само топ 5 
има мн грешки веќе се набројани д ане ги повторувам пак 
има нешто Freaky (ЧУДНО)
Секој напад по 1% Зима 16 пати нападнав 16% земам Зш така

**Comment by kiprooo** [comment]
za trkaloto: ako go imas na pr vo 1 saat stisnato ke moras i drugiot den da go stisnes vo 1 saat  

check it :) http://www.youtube.com/watch?v=DNXGSGCriyA&feature=player_embedded

**Comment by Hariss** [comment]
ГО гледав Клипот Quick  Малце скрати го и појак ќе биде :)

**Comment by skechboy** [comment]
@kiprooo голема пофалба за трејлерот. Keep it UP Respect :)

**Comment by kiprooo** [comment]
:) фала :D
