### ISSUE TITLE
Убивање и губење на сите пари

### ISSUE THREAD

**Issue by stevcooo** [skechboy/MAFIA#147]
Добро бе мајко му стара, како е можно тоа кога некој ќе те убие да може да ти ги земе сите пари и од банка??? стварно не ми е јасно, и сега иде работава џабе сум играл 10 дена сега треба пак се од ново, ама пред тоа да почекам 24 часа? стварно не е фер. На овој начин ќе посперираат само тие што почнале да играат први, секогаш ќе бидат појаки, и секогаш ќе можат да отепаат некој и да му ги земат сите пари. Дај направете нешто во врска со ова бидеќи ќе изгубите еден куп на играчи.
И мислам дека добро би било некаде да ги ставете сите правила на игра оти мн луѓе не се информирани како идат работите.
Поздраф.

**Comment by LPetar** [comment]
Затоа постои сеф, и откако ќе те убијат парите остануваат.

**Comment by hvardovski** [comment]
Се сложувам со ЛПетар, и плус ако не можиш да играш на мира или купи заштита или Дај почит на некого да те штити.ОВА Е МАФИА!!! нема милост.

**Comment by stevcooo** [comment]
а бе ок, немаф прочитано за тоа, и затоа така, во ред, од сега ќе знаам дека треба да се купи сеф и такви работи. Муабетот ми беше да се постават некаде правилата да се знае што  и како е, и мислам дека фали да може да видеш кое злосторство колку искуство ти носи!

а за тоа со почит за да те штити, не е се така розово :(, има еден куп што лажат само за почит да соберат.

**Comment by skechboy** [comment]
Гледам сте го нашле одговорот на прашањето :) @LPetar и @Kimsa  ви благодарам што му помогнавте на стевчо. Поздрав

**Comment by stevcooo** [comment]
а делот со Автомобили кога ќе биде пофторно во ред, бидеќи еве веќе неколу часови ја дава таа странциата со одбројувањето.
Поздраф
