### ISSUE TITLE
Макро а немози да се кради бугати и ...

### ISSUE THREAD

**Issue by Filipbt** [skechboy/MAFIA#148]
зс

**Comment by alekss** [comment]
HAHAHA, decko sansa za dobivka na Bugati ti e 0% kako moes da go dobies, koa ke bidesh lider ili kum togash ke go dobiesh

**Comment by lion4e** [comment]
taka e... no zoshto togash e otvoren Bugatti Veyron a ne se ni kradi.... toa e 4udnoto... ako e otvoreno toj sho probva neka odi v zatvor... :))
