### ISSUE TITLE
Проблем со коментарите

### ISSUE THREAD

**Issue by Pipelin** [skechboy/MAFIA#15]
Има еден мал проблем со коментарите доколку се пише нешто како //// или друг знак многу забегуваат како на сликава: http://pic.mk/images/mafiamk129.png гледаш десно излезени се од прозорчето каде што треба да бидат....

Eве на пример: http://pic.mk/images/mafiam1292430991.png и после доле страната се шири во хоризонтала...

**Comment by skechboy** [comment]
Проблемот е одстранет ти благодарам за посочувањето на  грешката. + Respect  :)

**Comment by Pipelin** [comment]
Да сега е ограничено, но доколку реченицата продолжува нема да се гледа, Дали може да се стави скролбар од десната страна или барем да се ограничи коментарот пример со 500 карактери. (предлог, идеа)

**Comment by skechboy** [comment]
доколку има празно место во реченицата таа автоматски ќе се префрли во нов ред. Овој проблем се појавува само кога има предолги зборови :)
