### ISSUE TITLE
Грешка (Баг)

### ISSUE THREAD

**Issue by DamDav159** [skechboy/MAFIA#151]
Ја крадам втората кола и ми успева.После ја продавам и ми пишува "Колата не ти препажа на тебе" и не ми ги даде парите а колата ја снема.Ве молам поправете.

**Comment by killer159** [comment]
pa ne e greska adminite napisale deka ne ti pripagatebe nemoze toa samo da se napisalo

**Comment by DamDav159** [comment]
abe greska e mene mi go napisa toa i ne mi gi dade parite.mateeeeej
