### ISSUE TITLE
Предлози

### ISSUE THREAD

**Issue by stefan96** [skechboy/MAFIA#154]
Играва е ок.Супер е што сте се сетиле да ни направите игричка да има кај времето да го тепаме:).
Уште подобра ќе биде ако воведете усте некои делови и слично.
Па имам некои предлози:
1.Да воведете чет каде што сите играчи ќе можат да зборуваат договараат и слично.
2.Можете да воведете усте игри на среќа, т.е коцка.Да направите казина во кои ќе има покер,рулет,машини и слично...
3.Да воведете нови претпријатија да се купат,или уште подобро да воведете берза на која ќе може акција да се купат, цената ќе зависи од побарувачката на истите или слично, може убаво да се разработи.
4.Убаво би било да воведете и нови градови,бродоградба,нови коли,оружје,работи и така.
кажете што мислите за овие предлози 
поздрав

**Comment by prokiller2** [comment]
see e superr moze jas so mi e interesno da se osnovat firmi
da imas rabotnici botovi i igracii ....

**Comment by stefan96** [comment]
pa moze uste dosta raboti da se dodadat ubavo bi bilo mnogu ubavo:D

**Comment by KP3T3H** [comment]
igrite na sreka ke se otvaraat pokasno vo igrata edna po edna

a za drugoto, mene ne mi se dopagja, a i ne veruvam deka ke go ima

**Comment by boge** [comment]
coll bi bila igrata da moze graganini da rabotat i da zimaat plata od 50.000 100.000
