### ISSUE TITLE
sakam da  gi prasam adminite i sakam da mi dadat odgovor na ova prasanje

### ISSUE THREAD

**Issue by sasko1** [skechboy/MAFIA#155]
jas pred 1 nedela otidov na gosti kaj bratucedmi i od tamu igrav mafia.Vcera mi se javi toj i mi rece deka ke napravi profili. Dokolku on napravi profil dali ke bidam jas baniran

**Comment by skechboy** [comment]
Не доколку пријавите за кои профили се работи.
