### ISSUE TITLE
Купување во градови

### ISSUE THREAD

**Issue by xBOJANx** [skechboy/MAFIA#157]
Нели треба да има одредени градови или пак држави(подобро градови) за у кој град со мозе да се купува.
На пример:во Скопје, Врање, Минхен и ..... да се продава орузје у други домасни работи и итн.
Вака не е добро от секој ден треба да патуваш ако сакаш нешто да купеш
Поздрав мислам дека така ке биде многу подобро

**Comment by hvardovski** [comment]
Ти и од пиле млеко да не сакаш

**Comment by skechboy** [comment]
Локацијата на продавницата се менува само заради распоредување на играчите рамногправно низ сите градови т.е. доколку продавницата за оружје биде стационирана во еден град сопственикот на транспортните објекти ќе биди многу поголеми печалби од продажбата на билетите за разлика од другите играчи.

**Comment by xBOJANx** [comment]
Ок тогаш веке знам како иде позз
