### ISSUE TITLE
Пријави опцијата во пораките не работи

### ISSUE THREAD

**Issue by Pipelin** [skechboy/MAFIA#16]
Не работи пријави опцијата кај пораките 

Слика: http://pic.mk/images/404notfoun.png

**Comment by skechboy** [comment]
Веќе е средено. Благодарам за известувањето.

**Comment by Pipelin** [comment]
За тест пријавив моја порака... :)

**Comment by skechboy** [comment]
Ќе бидеш баниран :D :D
