### ISSUE TITLE
Здраво другари :)

### ISSUE THREAD

**Issue by kiprooo** [skechboy/MAFIA#160]
Имам предлог: Ќе може ли да организирате награди како на пример: Најдобра лична порака и слично. Вие можете да смислите со што ќе ја зголемите љубовта на играчите кон мафиа.мк :) Поздрав и честитки Quick

**Comment by skechboy** [comment]
Твојот клип не натера да размислуваме за да организираме натрпевар за најдобар видео клип на тема MAFIA.MK па ќе видеме поззз

**Comment by kiprooo** [comment]
хех ок :) Навистина мафиа.мк е многу интересна. ЕДИТ: ГОРЕ треба да пишува најдобар личен профил, а не порака :) ахахаха
