### ISSUE TITLE
Има грешка кај златните пиштоли.!

### ISSUE THREAD

**Issue by Makedonija** [skechboy/MAFIA#162]
Обично долу кај златните пиштоли се појавуваат по 3 златни...Кога ке јас освежам страната останува 1 златен,а некој пат ме моти цел саат...Решете го проблемот бидејки готов сум да ме стават во затвор 24 часа.

**Comment by skechboy** [comment]
Прочитај го текстот над пиштолите кој пиштол треба да го селектираш ?

**Comment by deadwalker** [comment]
na mene mi se pojavija site zlatni pistoli a pisuva izberi go srebreniot pistol
nezz so e problemot

**Comment by skechboy** [comment]
@deadwalker освежи ја страницата со Ctrl+F5 и дали можеш да ни пратеш слика да видеме што е проблемот

**Comment by deadwalker** [comment]
ako mi ispadne uste ednas ovaka ke slikam
no ne mi tekna pred toa :S

**Comment by deadwalker** [comment]
http://pic.mk/images/greska1293327828.jpg

**Comment by deadwalker** [comment]
http://pic.mk/images/greska2.jpg
eve i toa mi se desava mn pati kliknam na ovaj pistol sto go bara i pak mi pokazuva da izberam

**Comment by Filipbt** [comment]
da mene ako pricnev pogresen uste ednas i 24 casa ke bev i na 44 sila bev

**Comment by deadwalker** [comment]
ako ti se pokazi ovaa ctrl+F5 i pak klikaj na pistolot

**Comment by KP3T3H** [comment]
eve nekolku pati mi se slucuva i mene

http://pic.mk/images/untitl1293331522.png
http://pic.mk/images/untitl1293331626.png

ni refresh ne pomaga mnogu pati, moze i cel saat da izgubam za da izvrsam edno zlostorstvo
 .
.

a mnogu pati se slucuva da ne funkcionira edinstveniot razlicen pistol

moja preporaka e da go vratite stariot sistem oti vaka ne ide

**Comment by ggggrand** [comment]
znaci ne cepkajte tamu kade sto veke si funkuonira

sto majka baravte da cepkate kade sto ne treba

vratete go po staro a ne se zaebavate tuka, pa nie ke odime u zatvor 24 casa zaradi vasa greska, 

namesto da zemete da popravite bagovite, vie se zaebavate tuka, sve ke rasipete ako prodolzite vaka
http://fotografija.com.mk/images/srebrenpistolftw.jpg

**Comment by Pipelin** [comment]
CTRL + F5

**Comment by deadwalker** [comment]
epa ako pravime refres treba po 5 min da vrsime edno zlostorstvo, raboti ili avtomobili

**Comment by deadwalker** [comment]
eve sto mi se sluci pred malce
http://pic.mk/images/21293357332.jpg

**Comment by pigmy** [comment]
Epa izberi go bronzeniot :))

**Comment by skechboy** [comment]
@mafioze пред да брмчиш освежи ја страницата со CTRL+F5 и ќе се реши проблемот поззз

**Comment by skechboy** [comment]
@deadwalker навистина не зачудува твојот проблем... моментално истражуваме што може да го предизвика тоа па доколки ти се појави повторно ова те молам извести не позз

**Comment by Makedonija** [comment]
Мене сега пред пет минути ми се појави,а сега ке видам како е ,а доколку пак имам 3 златни,ке сликам...

**Comment by Makedonija** [comment]
Трајче,Ми излегуваат три златни и еден сребрен,а горе над пичтолите ми пишува изберете го сребрениот пиштол.Од вас е направено така или има проблем ?

**Comment by Makedonija** [comment]
А некој пат е избери го златниот,почесто е исбери го златниот ама се менуваат.

**Comment by skechboy** [comment]
@Makedonija  да тоа е од нас направено така.

Доколку ти се појават 3 златни и еден сребрен пиштол треба да го избереш СРЕБРЕНИОТ, а пак доколу ти се појават 3 сребрени и еден златен треба да го избереш ЗЛАТНИОТ.

Ова промена ја направивме поради тоа што имаше играчи кои го злоупотребуваа стариот систем на пиштолите. 

Поздрав

**Comment by Makedonija** [comment]
Благодарам.
Поздрав !

**Comment by Makedonija** [comment]
Трајче,Повторно има проблем.
Проблем 1.Ми бара по двапати да кликнам на пиштолите.
Проблем 2.Сега пак пред малце,сите четири ми беа златни.Неможев да сликам бидејки стара ми е тестатурата,другата ми е на другиот компјутер.

**Comment by KP3T3H** [comment]
ova so tri isti pistoli se pojavuva veke po sto pati a bara eden od niv, dzabe e i refresh pak isto se pojavuva
http://pic.mk/images/11293371812.png
http://pic.mk/images/21293371836.png

mnogu pati se slucuva edinstveniot razlicen pistol da ne raboti

dajte popravajte go ova brzo, ne se igra vaka

**Comment by skechboy** [comment]
@KP3T3H  од сликите може да приметам дека имаш отворено повеќе табови во играта, па можам да пртпоставам дека истите ти се отворени на ралични локации каде што има златни пиштоли 
т.е. отвараш на работа и потоа во нов таб крадење на автомобили. Токму ова го предизвикува тој проблем. 

Мој совет е кога сакаш да извршуваш нешто каде што има златни пиштоли да не ги отвараш во нов таб барем сега за сега но наскоро ќе го решиме и тој проблем поздрав

**Comment by Makedonija** [comment]
Мој предлог е се да остане по старо.

**Comment by KP3T3H** [comment]
ok, mozno e da e toa, no cesto pati se slucuva i edinstveniot razlicen pistol da ne raboti......

**Comment by vasko11** [comment]
i kaj mene se pojavuva 3 zlatni pistoli neznam koe da go kliknam pritiskam 
CTRL + F5 nebiva si ostanuva isto.

**Comment by skechboy** [comment]
vasko11 доколку го прочиташ текстот веднаш над пиштолите ќе забележиш дека треба да го избереш сребрениот пиштол.

Доколку ти се појават 3 златни и еден сребрен пиштол треба да го избереш СРЕБРЕНИОТ, а пак доколу ти се појават 3 сребрени и еден златен треба да го избереш ЗЛАТНИОТ.

**Comment by vasko11** [comment]
ok blagodaram neznaev, 
ali poarno e po staro.

**Comment by KP3T3H** [comment]
pistolite ne se namesteni tocno ako ja odzumiram stranata
pic.mk/images/zoomout.png
koe sto ne se slucuvase po stariot sistem....

**Comment by hvardovski** [comment]
HAH http://www.pic.mk/images/hah1293453952.png

**Comment by JackDaniel** [comment]
Јас користам Mozilla Firefox и не гледам дека вакви проблеми се појавуваат кај мене , http://www.pic.mk/images/hah1293453952.png  ако го имате овој проблем
не се активирајте во игра преку Google Chrome туку логирајте се преку  Mozilla Firefox . . . и мислам дека проблемот ќе биде решен !

**Comment by deadwalker** [comment]
kaj mene se sredi

**Comment by DVL-b7** [comment]
еве и мене ми се појавија два сребрени два златни и ми вели одбери го сребрениот пиштол...... 
http://pic.mk/images/mafiagresk.jpg

**Comment by DVL-b7** [comment]
еве уште едно http://pic.mk/images/s1293614003.jpg

**Comment by ChillmaxTM** [comment]
ако три пиштола се златни притисни на сребрениот пиштол

**Comment by LakiSema** [comment]
Бре Бре Ама сте прости ! ЗНАЕТЕ ЗОШТО ВИ СЕ ПОЈАВУВААТ ПО 3 ЗЛАТНИ ПИШТОЛИ  И ТРЕБА ДА КЛИКНЕШ НА ЗЛАТНИОТ ? - ЗАТОА ШТО УКЛУЧУВАТЕ НА ПОВЕКЕ ТАБОВИ... ЕДЕН ТАБ Автомобили Друг Таб ЗЛОСТОРСТВА Трет Таб Дрога Четврт Работа 

значи ако играш на еден таб. нема никакви шанси да ти се појават 3 златни и  да треба да кликнеш на златниот .. позз до skechboy

**Comment by ChillmaxTM** [comment]
jas igram na 1 tab i toa bak mi pravi taka toa nema vrska ti sto kazuvas

**Comment by LakiSema** [comment]
epa togas neznam ... kaj menee taka koga otvoram poveke tabovi se meshaat :)

**Comment by DroWRaNgeR** [comment]
LakiSema nema vrska toa sto go kazuvas  i jas igram na eden tab pa pak nemozam 
ama nemozam od Mozila Firefox
install si go GoogleChrome i ke nemate nikakvi problemi pozz do site

**Comment by ChillmaxTM** [comment]
jas na Opera

**Comment by Trajkovski** [comment]
Jas na mozila
