### ISSUE TITLE
Голем Баг !!! Ве молам погледнете !!

### ISSUE THREAD

**Issue by Kristijan40** [skechboy/MAFIA#163]
Има голем баг тоа често ми се случува кога ќе идам во Менито Злосторства и изберам кое злосторство ќе го вршам треба да кликнам на златниот пиштол нели? Епа кај мене понекогаш има повеќе златни пиштоли !!Имам и слика ама очигледно неможе да се прикачува слики !!

**Comment by skechboy** [comment]
Доколку го порчиташ текстот веднаш над пиштолите ќе забележиш дека треба да го избереш сребрениот пиштол :) позз
