### ISSUE TITLE
Грешка

### ISSUE THREAD

**Issue by Nexus123** [skechboy/MAFIA#165]
Зошто сега ми вика избери го сребрениот пиштол а некогаш па избери златниот пиштол?
Немојте овака зашто е збунувачки

**Comment by skechboy** [comment]
Направивме мала промена во системот со пиштолите. Ја направивме оваа поради тоа што имаше играчи кој го злоупотребиуваа стариот систем. Свесни сме дека на многу играчи ќе им треба време да се прилагодат на оваа промена и затоа доколку го згрешите пиштолот 3 пати нема да влезете во затвор на 24 часа :) :) Поздрав

**Comment by LPetar** [comment]
Грешката е пријавена, оваа е 3та тема.. скеч одговори дека се работи на проблемот.
