### ISSUE TITLE
Предлог

### ISSUE THREAD

**Issue by Krichi** [skechboy/MAFIA#166]
Мислам дека треба да се намали цената на дрогата. Еве рецимо купиш 1 кг марихуана за 50.000€ и наредниот ден ја продадеш да речеме за 5.000€ или 10.000€. Тоа не се ни малку исплати бе.

**Comment by Makedonija** [comment]
Не се согласувам,дрогата си е добра.

**Comment by Makedonija** [comment]
За 1 недела парите што си ги дал за дрога,ке си ги вратиш.

**Comment by skechboy** [comment]
Цената на дрогата е висока поради тоа што сакаме во играта да има што помалце пари со што се зголемува вредноста на парите кое исто така ги стимулира играчите да се напаѓаат повеќе меѓу себе.
