### ISSUE TITLE
Kafeterijata na dava pari!

### ISSUE THREAD

**Issue by shadowrider1** [skechboy/MAFIA#167]
Vcera kupiv 5 kafeterii i vika po 1 cas deka dava 500 mene ne mi dava nisto! Da vidam dali e vistina toa gi izvadiv site pari od Narodna banka na RM i si gi staviv vo sef i koga se ukl posle 2 casa gledam 500 vo narodna banka na RM i 100 vo kes a toa e od taen link!

**Comment by shadowrider1** [comment]
Ne dava pari!

**Comment by skechboy** [comment]
Проблемот е решен. Ти благодарам за известувањето. Очекувајте ги парите од кафитериите во 20ч и како што е редот секој час понатаму. Позз

**Comment by shadowrider1** [comment]
ok fala!
