### ISSUE TITLE
Чиста грешка!

### ISSUE THREAD

**Issue by kuche** [skechboy/MAFIA#168]
кој знае математика? нека израчуна колку вкупно изнесува од сите 4 коли VW Golf IV
http://fotografija.com.mk/images/1lfl.bmp

-грешката е http://fotografija.com.mk/images/2czc.bmp видете колку пишува од тие 4 коли ОМГ

**Comment by killer159** [comment]
abe tamu ti pisuva broj 4 ne gledas?

**Comment by kuche** [comment]
а ти ако си писмен одма ќе ја разбереше работата.
еве јас ќе ти кажам 12730+15390+14440+13300=55860 
,што пишува на втората слика?колку е износот од сите 4 коли?

**Comment by KP3T3H** [comment]
таму не знаеш дали се оштетени или не, затоа ја дава максималната вредност на колите
