### ISSUE TITLE
Поправете го проблемот со КАФЕТЕРИИТЕ!

### ISSUE THREAD

**Issue by riba** [skechboy/MAFIA#169]
Купив 3 кафетерии.И секоја дава по 500$ на час што значи за  1 час 1500. Пред да си легнам во 22:00 ВО КЕШ и во Народна Банка на Р.М оставам 0$. Кога станувам во 6 часот во кеш имам 600$ а во Банката имам 3000$ а треба да имам 12000$. И тие 3000$ што ги имам тие со од таен линк итн. Дај решете го проблемот.

**Comment by skechboy** [comment]
Проблемот е решен. Ти благодарам за известувањето. Очекувајте ги парите од кафитериите во 20ч и како што е редот секој час понатаму. Позз

**Comment by riba** [comment]
Фала ви многу. :*

**Comment by riba** [comment]
А што е со автомобилските трки?
Кога се тркаш дење, веројатноста да бидеш фатен од полицијата е многу голема, а пак навечер има поголема веројатност да си ја оштетиш колата.
Кога треба да се тркам и како да ја завршам мисијата ?
