### ISSUE TITLE
Таен линк сликичето не е линкувано

### ISSUE THREAD

**Issue by Pipelin** [skechboy/MAFIA#17]
Порано на старата мафиа имаше ако ти кликне некој на таен линк, ти од десната страна на тоа портокаловото клуче да му вратиш. Сега тоа не е линкувано на оваа верзија

Слика: http://pic.mk/images/mafiam1292431328.png

Од десна страна ТЛ сликичето не работи т.е неможам да им вратам...

Дали ова е грешка или така е намерно направено, незнам.

Горе може да се пише наместо: Ова е листата од корисници кои го кликнале твојот таен линк во последните 24 часа.

Да пишува: Ова е листата од Мафијаши кои го кликнале твојот таен линк во последните 24 часа.

**Comment by skechboy** [comment]
Проблемот е исправен ти благодарам за известувањето.
