### ISSUE TITLE
Автомобислки трки ?

### ISSUE THREAD

**Issue by riba** [skechboy/MAFIA#170]
А што е со автомобилските трки?
Кога се тркаш дење, веројатноста да бидеш фатен од полицијата е многу голема, а пак навечер има поголема веројатност да си ја оштетиш колата.
Кога треба да се тркам и како да ја завршам мисијата ?

**Comment by skechboy** [comment]
Најдобро е да се тркаш навечер и со што побрза кола кое ти ги зголемува шансите за победа.

**Comment by riba** [comment]
Aхам благодарам.
