### ISSUE TITLE
Предлог

### ISSUE THREAD

**Issue by riba** [skechboy/MAFIA#172]
Мисијата за автомобилски трки како што разбрав се завршува со појаки автомобили односно автомобили од категоријата Брзи автомобили и Топ5. Зборот ми е мисијата да не биде уште на почеток ставена да биде меѓу последните мисии. Бидејќи тие што се уште почетници таман ќе октрадат некоја кола т.с. од првата класа послабиде таман ќе открадат некоја слаба и ќе ја изгубат. Така да предлог од мене мисијата да биде подместена помеѓу последните мисии.

**Comment by KP3T3H** [comment]
ако не сакаат да ја изгубат колата нека не идат да се тркаат, мисијата си е на место нема потреба да се поместува во напредни мисии
