### ISSUE TITLE
Грешка (Дрога)

### ISSUE THREAD

**Issue by riba** [skechboy/MAFIA#175]
Ова ви е мислам премногу голема грешка е сега дали намерно така а правите незнам. 

500k \ 50k  =   10kg  = 45530
500k \ 75k  =   6.6kg = 41547
500k \ 100k=   5 kg   = 36555
500k \ 250k=   2kg    = 18432
k= илјади

Значи до овде до екстазите најмногу се исплаќа да купуваш марихуана. Ова 500к (500 000) ми е така просечна сума и кога ќе ја поделиш со сумата на првиот вид на дрога излегува толку кг (10 кг) и кога ќе ја помножиш со најскапата цена од сите држави излегува  45530 и потоа пак истите пари ги поделувам на овој начин и се помалку и помалку пари изнесува. До екстазите потоа се накачува незнам дали ме свативте но ако ме свативте. Пишете ми одговор. Позз

**Comment by KP3T3H** [comment]
поентата на оваа верзија е да се игра со помалку пари, 

инаку сваќам што сакаш да кажеш

**Comment by riba** [comment]
Да, за тоа сваќам да се игра со помалку пари и така е и поинтересна ако има повеќе пари нема да биде интересна. Но да биде израмнето да иде постепено. Значи првата да дава толку втората малку поскапо третата уште малку поскапо а не обратно. Штом е така добро јас да пишав да не беше некоја грешка.

**Comment by KP3T3H** [comment]
значи ако го израмниш производството на дрогата на сите видови на пример 20кг, ќе видиш дека секоја наредна дрога дава повеќе пари од претходната, тука јас не гледам никаква грешка.

**Comment by riba** [comment]
Да али ај размисли малку 20кг марихуана да ја купиш по 50 000 и 20 кг халуцигени печурки изнесуваат различна сума на пари. Зборот ми е да имаш моментално 500 илади како што пишува горе и за тиа пари најмногу ти се исплаќа марихуаната и погледни зошто имам пресметано и објаснето е како е пресметано. Неможеш уште да ме разбереш. И  потоа ќе види оти наредната дрога дава помалку.

**Comment by flexMK** [comment]
pojshe vlozuvash a pomalec dobivash :)  na pr 10 kila ako staam marihuana dur da si gi vratish parite ke se zaboraish :)

**Comment by riba** [comment]
epa istite pari da gi stavis na druga droga pobavno ke si gi povrnis toa sakam da go kazam :) ne a glej koli4inata na drogata gledaj ja sumata na parite sto ja vlozuvas.  Na pr. isti pari da stavis na marixuana i na xalucigeni pecurki pobrzo ke si gi povrnis na marixuanata a obratno trebe da bide :)

**Comment by ChillmaxTM** [comment]
Многу е скапа дрогата. Ако може да се смали на марихуаната 40 000, 30 000, 20 000, 10 000 евра  но и другите дроги за да биде повеќе реално. Екстазите се 1 000 000 евра не ти се исплати да купуваш многу е скапо.

**Comment by KP3T3H** [comment]
епа ај нека тргнат по една нула од сите цени, и ќе биде најубаво
марихуана 5.000 евра
укради лижавче 5 евра
градежен работник 10 евра
поени за напад 500 евра
таен линк дава: 10 евра кеш, 50 евра банка, 10 моќ :D
итн. итн.

тоа ли сакате да стане :) , ако мислите дека ќе ги намалат цените се лажете

**Comment by riba** [comment]
Не бе брат не ти зборував затоа во дрогата излегува најмногу да се исплаќа за марихуана а најмногу треба да се исплати за последното за 1М да земеш последниот вид на дрога дава помалку одколку да земеш за тие пари марихуана повеќе ке земеш. Значи сакам да кажам најмалку да се исплаќа на марихуана па потоа постепено да се накачува. Ако ме свати ама не верувам.

**Comment by KP3T3H** [comment]
riba, не ти одговарав тебе, се надоврзував на igorbest

а иначе тоа што највеќе се исплати марихуана да купиш наместо овие другиве, си е точно

**Comment by riba** [comment]
Ахам.Така ќе остане марихуаната најскапа да биде ?

**Comment by ChillmaxTM** [comment]
Продажната цена на дрогата да се качи. Многу малку пари ти дава. Купуваш 1 килограм марихуана ја продаваш за 4000 и нешто евра.

**Comment by donstavros** [comment]
Ovde ja kupivas drogata 50000 ja prodavas za 4000
Na beta verzijata ja kupuvas drogata 7.500 a ja prodavas 1000

**Comment by riba** [comment]
Ај не ја менувајте темата (не излегувајте надвор од поставената тема). И продажната цена на дрогата е сосема добра. Но има еден проблем кој што е поставен погоре и за кој админите не се замарат.

**Comment by ChillmaxTM** [comment]
Нај убаво да се купува 50 000 евра, а да се продава за 25 000 евра напола.

**Comment by riba** [comment]
Арно е тоа и не коментирај веќе глупости кога ќе имаш Марихуана 1000 кг и Печурки 1200 ќе видиш дали е малку 4900 цена да биде.

**Comment by ChillmaxTM** [comment]
e jas nemam tolku

**Comment by riba** [comment]
Што ме интерсира дали имаш ќе си направиш.
