### ISSUE TITLE
Bag vo tajniot link 

### ISSUE THREAD

**Issue by flexMK** [skechboy/MAFIA#176]
znaci imav 8350 mok sega imam 8500 mok a nishto ne sum kupil  znaci mi klikale na tajniot link a koa ke ja otvoram listata vo tajniot link e ista :/ popravete go toa nemozam da im vrakam na lugeto.. pozz

**Comment by DiChOoO** [comment]
Истото е и кајмене.. Ако некој ти кликнал а ти да му немаш кликнато на тајниот линк ќе ти го дава со жолт клуч, а ако му имаш кликнато тој кога ќе ти врати нема да ти го покаже.. Али незнам зошто така направиле админиве..

**Comment by KP3T3H** [comment]
глупо е така, незнам колку души ми имаат кликнато и ако сакам да го ресетирам тајниот линк, незнам дали ќе се исплати

**Comment by DiChOoO** [comment]
Ќе се исплати..

**Comment by KP3T3H** [comment]
ќути си...................

може ми имаат вратено 100 души, така нема да ми се исплати

**Comment by DiChOoO** [comment]
Нема да ти се исплати.. Ако не те покажува кај нив џабе е.. Арно викаш..
