### ISSUE TITLE
Грешка со златниот пиштол

### ISSUE THREAD

**Issue by kiprooo** [skechboy/MAFIA#178]
ми се појавуваат 3 златни пиштоли, а еден е сив. И првиот пат незнаев што да стиснам и го стиснав сивиоти сеушто само сивиот пиштол го кликам, а не златните

**Comment by DiChOoO** [comment]
Следниот пат читај над клучевите кој клуч треба да го кликнеш.. Дали златниот дали сребрениот..

**Comment by KP3T3H** [comment]
читај што пишува над пиштолите, избери го сребрениот/златниот пиштол, т.е. еден од 4-те е различен.

**Comment by kiprooo** [comment]
owh posto na starata verzija ne bese vaka
