### ISSUE TITLE
Абе шо е ова

### ISSUE THREAD

**Issue by ljubomirkoteski** [skechboy/MAFIA#180]
Абе аман како можи да ме нападни во рок од еден сат повеќе од 5 пати а јас ко пробав еден да го нападнам ми пиша дека неможи фазла од 5 
[img]http://pic.mk/images/mafia1293534240.jpg[/img]

**Comment by DiChOoO** [comment]
Хахахахахаха ! Гледај малце бре не се прави слеп.. 5 пати те нападнал во 05 часот и 4 пати те нападнал во 06 часот.. Гледај малце а не одма да се пријавува како грешка..

**Comment by skechboy** [comment]
Доколку заприметиш подобро Puco_mkd те нападнал 4 пати во 6 часот и 5 пати во 5.

**Comment by KP3T3H** [comment]
дупли акаунти, две мафии, два броусери

**Comment by ljubomirkoteski** [comment]
Салам сте или глупи сосила се прајте
Од 5,37 до 6,19 има 42 минути а не 60 шо значи дека во рок од 60 минути можи да напаѓа 5 пати а не вака кога сака

**Comment by skechboy** [comment]
@CoCoKiller нема потреба од навреди очигледно е дека си нов во играта па ќе ти пообјаснам некои работи. Навистина си е на место твојота забелешка но еве како одат нападите во играта:

Значи бројот колку пати е нападнат некој играч се рестартира на секој час т.е. доколку некој играч е нападнат во 1:01 часот 5 пати по ред, ќе мора да чекате до 2 часот за да можете повторно да го нападнете, а пак доколку некој играч го нападнете во 1:59 пет пати во 2 часот ќе можеш да го нападнеш повторно. Тоа е причината за за ова недоразбирање. Поздрав

**Comment by ljubomirkoteski** [comment]
Ова е вејчем друго а не како шо вели да не бидам слеп оти ме нападнал во 5 и во 6 сато и да обвинува за дупли акаунти и не знам уште шо
Иначе разгледај те го ова за понатаму оти во вакви моменти има значајна предност, 
јас се пуштив негде после 6 30 и да не беше ова че успеев да се спасам па затоа сум малце изнервиран
