### ISSUE TITLE
ЦЦЦ не ми се верува

### ISSUE THREAD

**Issue by ljubomirkoteski** [skechboy/MAFIA#181]
Абе вие Сами глупи се прајте или од мајка сте родени
Во 1 сат има 60 минути а тој ме напајџа 9 пати во 42 минути
или ова е дупка во законо шо не ја зна сите па кој сака можи да ја користи
ако важат нека важат правилата за сите а не само за одредени
[img]http://pic.mk/images/mafia1293534240.jpg[/img]
И ко не знајте нетуку обвинувајте за дупли без врска само шо има два броусери уклучено незначи ништо

**Comment by ljubomirkoteski** [comment]
И плус то администраторите на играта да неможи да се напајџаат
ХА ХА ХА 
По ова се гледа дека кој шо сака то си прај во играва типично за македонци

**Comment by skechboy** [comment]
@CoCoKiller администраторите на играта се намо надзорници во неа, значи не играме и не се натпреваруваме како сите играчи. Ние само набљудуваме и го одржуваме "мирот" и редот во играта на првото прашање ти дадив одговор во претходниот пост. Поздрав
