### ISSUE TITLE
skech imam predlog

### ISSUE THREAD

**Issue by Kradec** [skechboy/MAFIA#182]
koga ke se kradat koli da e max cenata ne tamu pisuva Toyota prius i koga ke gu ukrades neli 16 000 e najveke na tebe ti dava pomalku zavisi kolky e ostetena ! toa predlozuvam da go nema i koa ke krademe so full ceni da gi imame kolite...

**Comment by riba** [comment]
Не ми се допаѓа!

**Comment by Kradec** [comment]
pa koj te tebe prasuva!

**Comment by riba** [comment]
Јас си кажувам мој предлог што не е јасно ?

**Comment by Kradec** [comment]
ti gledas li gore be skech pisuva i nego go pitam moze li ili ne

**Comment by KP3T3H** [comment]
ти за да украдеш кола, што ќе направиш, најверојатно ќе скршиш прозор, ќе ја обиеш бравата, после да ја запалиш сигурно немаш клуч, значи ќе треба жици да сечеш, и кога ќе видиш, ете ја штетата.....

и нема да биде реално ако без ич штета ја украдеш, сигурно нема да ја најдеш оставена отворена, и со клуч внатре :)

**Comment by riba** [comment]
Потполно се согласувам со КР3Т3Н

**Comment by Hellmafiamk** [comment]
Кретен у право е, но тогаш процентот на оштетата да биде помал на некоја кола, а не поголем, кога си повисок ранг.
пр. ранг Граѓанин ќе украде Тојотата оштета -> 1 - 5% оштета
ранг Џебџија ќе ја украде истата кола ќе има поголема оштета...
Поголем ранг помала оштетеност на колите, стекнуваш искуство со секој ранг...

**Comment by hvardovski** [comment]
Вака како што е најубаво е.

**Comment by riba** [comment]
Што му е најубаво место кога имаш најмногу искуство да имаш најмала штета он обратно кога имаш најмалку искуство најмала оштета и сега сум на пример убиец 10% и имам 27 илади искуство и требе од 5 до 10% да се движи штетата а не од 30 до 40% и што ќар е тоа ? :!@

**Comment by Kradec** [comment]
pogolem rang pogolema osteta !!! vo graganin ja koga bev ja kradev i ja prodavav za 15.000 a sea za 12.800 i 13.000 we hellmafiamk

**Comment by riba** [comment]
Едно зборуват друго прават.
