### ISSUE TITLE
Предлог (Дрога->Како да произведувам повеќе?)

### ISSUE THREAD

**Issue by riba** [skechboy/MAFIA#183]
Во делот Како да произведувам повеќе? мислам дека малку се овие  150 платени убијци да се направат. Предлог да бидат 500. А за победени битки и Убиени мафијаши е таман. Ама за ова Платени убијци ми стојат малку.Барем 500 да бидат.Позз

**Comment by kuche** [comment]
koe be taman ti ljutkav li si ?
mene ne mi e jasno so ubistvata kako reguliraat:@ 
1viot 4 ubistva bara 
2riot 12 ubistva
3tiot 24
4tiot kolku ?
toa ne mi e jasno:@ 
jas mislam deka ova e preterana rabota:@

**Comment by riba** [comment]
za ponataka neznam epa eve vaka mozhe da se napravi Платени убијци за првото надградување да биде 500 платени убијци 200 победи и 4 убени мафијаши за второто да биде 500 платени .... 200 победени битки... и 8 убиени мафијаши... и се така за дупло... незнаев дека за второто е 12 убиства епа многу е барем нека се зголемува за дупло..

**Comment by skechboy** [comment]
Платените убијци, убиствата и победите потребни за зголемување на капацитетот на дрогата се зголемуваат експоненцијално со што ќе биде многу потешко да се стигне до х10 од максималниот капацитет како што беше на бетата.

**Comment by riba** [comment]
Ок , но во дрогата најмногу се исплаќа марихуаната, што треба да биде обратно.Тоа не ми се допаѓа.
