### ISSUE TITLE
Мисија: Патувај до друг град

### ISSUE THREAD

**Issue by klikstermkd** [skechboy/MAFIA#187]
Мисијата се извршува откога ќе го купам билетот. Зарем не е логично да се изврши од кога ќе се пристигне до саканата дестинација? Бидејќи како што е сега, пример можам да го откажам патувањето а мисијата ќе ми биде извршена. :)

**Comment by skechboy** [comment]
Да во право си но сепак некогаш ќе мораш да патуваш. Како и да е мисиите се направени за играчите побрзо да ја сватат суштината на играта, а со тоа што веќе купиле билет ни дава на знаење дека го совладеле тој дел од играта.
