### ISSUE TITLE
GOLEMA GRESka

### ISSUE THREAD

**Issue by Kradec** [skechboy/MAFIA#193]
ADMIN SAKAM DA GO NAPADNAM loverrr toj e rang potrcko 0.25% i mi pisuva vaka:

ГРЕШКА!!!
Мафијашот кој сакате да го нападнете е премногу слаб.
Најдете си достоен противник, некој кој кој е со поголем ранг од Поттрчко.

**Comment by ljubomirkoteski** [comment]
И мене така ми дава за поттрчковците

**Comment by KP3T3H** [comment]
вашиот ранг е голем :)

иначе кој ранг сте.

**Comment by Kradec** [comment]
kradec sum rang

**Comment by riba** [comment]
Добро е ова направено. Оти се креират многу нови јузери и си местат убиства. Добро е малку касно ви текнало но пак на време е.

**Comment by riba** [comment]
Добро е ова направено. Оти се креират многу нови јузери и си местат убиства. Добро е малку касно ви текнало но пак на време е.
