### ISSUE TITLE
ГРЕШКА ВО ЗЛОСТОРСТВА

### ISSUE THREAD

**Issue by kikec2000** [skechboy/MAFIA#196]
ИМА ГРЕШКА ВО ЗЛОСТОРСТВА КОГА ЌЕ ТРЕБАШ ДА ГО ИЗГРЕБЕШ ЗЛАТНИОТ ПИШТОЛ ИМА 3 И МИ ВИКА ТИ 2 ГО ПРОМАШИ!!!АКО ГО ПРОМАШИШ УШТЕ ЕДНАШ ОДИШ ВО ЗАТВОР,А ЈА НЕЗНАМ КОЈ ДА ГО СТИСНАМ!

**Comment by KP3T3H** [comment]
читај дали треба да го стиснеш златниот или сребрениот
