### ISSUE TITLE
admin

### ISSUE THREAD

**Issue by Kradec** [skechboy/MAFIA#197]
preporacuvam da se izbrisat site 4itovi so postojat za mafia.mk oti ne e fer sprema drugite.. kako na pr prdle ima 4it 10000%

**Comment by DiChOoO** [comment]
prdle nema chit.. gledaj mu go rangot.. so toj rang ima golemi shansi za kradenj na bugati.. ne go chuva, odma go prodava i vo sef gi chuva parite.. a i mnogu drugi ke se istaknat i pred prdle.. ostaj ti sho vito igra nekoja igra sho kreva mokj samo.. site ke padnat ;)

**Comment by Kradec** [comment]
dicho  aj staj me pod tvoja zastita :D

**Comment by DiChOoO** [comment]
Zasluzhi prven :))
