### ISSUE TITLE
Problem so napaganje na mafijas

### ISSUE THREAD

**Issue by deadwalker** [skechboy/MAFIA#199]
ima nekoj problem so napaganjeto na mafijas koga napagjam mafijas go napagam ednas i mi broi kako da sum go napadnal 5 pati zs e taka
i mu zema malce zdravje ve molam resete go problemov

**Comment by lion4e** [comment]
mozi toj da e poslab so 100tina poeni mok a ustvari ima povejke plateni ubijci od tebe... a sho povejke ubijci tie se vazhat kako pojke mok...i ti gubish vo taa bitka... barem taka beshe na betata kolku sho znam... ;)) pozz

**Comment by lion4e** [comment]
mozi toj da e poslab so 100tina poeni mok a ustvari ima povejke plateni ubijci od tebe... a sho povejke ubijci tie se vazhat kako pojke mok...i ti gubish vo taa bitka... barem taka beshe na betata kolku sho znam... ;)) pozz

**Comment by deadwalker** [comment]
ma ja pobeduvam bitkata ama pravo mi broi za 5 pati

**Comment by lion4e** [comment]
e toa nzz.... :S

**Comment by donstavros** [comment]
Epa  sigurno koga si go napadna pred toa go napadnale 4  pati i zatoa

**Comment by prokiller2** [comment]
да навистина и јас прпат го гледам беше на 6 сила го напагам ми вика сум го нападнал 5 пати 

Јас милам дека ти мафиаши се од админите заштитени за они да си ги отепаат некој е админ и сеа ке прави се со сака :@
