### ISSUE TITLE
Грешка во информациите кај Профилот!

### ISSUE THREAD

**Issue by Pipelin** [skechboy/MAFIA#2]
Кога ќе го отвориш делот од профилот каде што е, има два реда каде што пишува 
Заштита од државата: 10 часа
Заштита од државата: 0 часа

Дали е ова исто, според мене треба само да е едно... 

Еве слика: http://pipelin.ws.mk/files/profil.png

**Comment by skechboy** [comment]
Грешката е исправена ти благодарам за известувањето
