### ISSUE TITLE
Проблем со затворот

### ISSUE THREAD

**Issue by Pipelin** [skechboy/MAFIA#20]
Има баг со затворот. Кога влегуваш во затвор кога ќе те фати полицијата кликаш на пораките и потоа можеш повторно да работиш, да извршуваш задачи. Додека пак кај старата ако случајно бидеш во затвор единствено што можеш е да ги прочиташ пораките.

Во овој случај затворот како да не работи. Пробајте да влезете во затвор, и кликнете на пораките горе десно и потоа можете да работите, да крадете коли и друго, иако сте во затвор :)) 

Се надевам ова ќе се среди.

**Comment by skechboy** [comment]
Грешката е одстранета :)
