### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by lion4e** [skechboy/MAFIA#200]
neznam dali e error... ako moze da mi objasni skechboy...
koga ke odam na nekoja rabota... ke ja izvrsham , ke ukradam kola, ke izvrsham zlostorstvo ( ke uspeam ) ne mi dava ni najmal % na rank... ako mozhi pojasnuvanje.. tnx pozz

**Comment by donstavros** [comment]
Da taka e jas 100 pati probuvam rabotam kradam koli izvrsuvam zlostvorsva i uspevam a ne se diga ni 1% rank ve molime da ja popraviti taa greska

**Comment by xBOJANx** [comment]
epa posle po golemite rangovi e potesko ta kazes
na primer za 5 % da dignes na kradec  treba najmalku 20 pati da kliknes rabota,avtomobili,zlostorstva
 pozzz

**Comment by lion4e** [comment]
ti brat ne me razbirash...3 pati da napram ubava rabota( Haker ) 100% zlostorstvo sho mie i avtomobil posledniot ( Bugatti Veyron ) ne mi davashe mislam deka imashe nekoj problem a i sega ima... dokolku e nekoj problem go molam skechboy da ni kazhi barem... da znam zoshto pomalce % krevam :S pozz

**Comment by donstavros** [comment]
Brat ama toa bese uste koga bev gracanin
