### ISSUE TITLE
Предлог

### ISSUE THREAD

**Issue by NonameMkD** [skechboy/MAFIA#204]
Предлагам во следната верзија да ставите и теретана. Не знам колку е изводливо, но сепак мислам дека би било интересно... да можеш да вежбаш гради, плеќи, раце, нозе... па со определена тежина... а со тоа и во продавницата да се вметнат протеини, гејнери, стероиди... Ова да има некаква врска со моќта или здравјето, пошто сепак, колку повеќе „набилдан“, толку посилен :D Може да се реализира ова, или тешко?

**Comment by lion4e** [comment]
jas sum ZA brat... :)) super predlog !!!!!!!!!!

**Comment by NonameMkD** [comment]
Фала за поддршката лионче :)

Некој друг го видел ова, или слабо?

**Comment by stefan123** [comment]
Interesno ... :D

**Comment by lion4e** [comment]
nema problem brat... samo da uspej ova ke se ostajvme v teretana... xD :))) pozz

**Comment by barcellona** [comment]
Ја сум за

**Comment by NonameMkD** [comment]
а дали некој админ ја видел темава? :/
