### ISSUE TITLE
Болница - грешка

### ISSUE THREAD

**Issue by klikstermkd** [skechboy/MAFIA#207]
Кај болницата и без да го поместиш лизгачот колку сакаш да се излекуваш кога ќе притиснеш на пиштолот ќе те излекува 100%.

**Comment by barcellona** [comment]
Да сум приметил.

**Comment by klikstermkd** [comment]
Вака е и подобро бидејќи во најголем број случаи сакаш да се излечиш 100% па да не губиш време на секое :)

**Comment by skechboy** [comment]
Како што кажа кликстер, не станува збор за грешка напротив намерно е направено така за да лечењето биде поедноставно.
