### ISSUE TITLE
Предлог за дрогата

### ISSUE THREAD

**Issue by ChillmaxTM** [skechboy/MAFIA#209]
Може ли на сите дроги за продажната цена да се накачи. На пример еден килограм  марихуана за да се купи е 50 000 евра, а продажната цена да е 25 000 евра напола од цената, и сите дроги така да бидат оти не ти се исплати.
1 000 000 евра е 1 килограм екстази , а продажната цена 45 000 евра подобро да биде 500 000 евра половина од цената за купување мислам дека ме разбравте. ПОЗЗ

**Comment by Wizardx** [comment]
hah taka so ke prajme site ke se iznazemat pari mn evtino idi

**Comment by ChillmaxTM** [comment]
cenata za prodavane naka si ostane tuku prodaznata cena da si zgolemi
