### ISSUE TITLE
Ослободување од затвор

### ISSUE THREAD

**Issue by Pipelin** [skechboy/MAFIA#21]
Неможам никого да ослободам од затвор, без разлика која е сумата едноставно не ми дозволува да извадам никого, дали е ова грешка?

Ми се појавува ова: 

ГРЕШКА!!!
Не можеш да ја платиш кауцијата за овој затвореник.
Затвореникот ќе биде наскоро ослободен поради добро однесување

**Comment by skechboy** [comment]
Може да се каже како намерна грешка т.е. беше наместено за да ослободиш некој мафијаш мора да има над 2 мин казна. Како и да е времето е намалено на над 1минута.
