### ISSUE TITLE
ADMIN AJ DA VIDAM KAKO KE GO OBJASNIS OVA?

### ISSUE THREAD

**Issue by Kradec** [skechboy/MAFIA#212]
IGracot danev15  go napadnav imase 5 sila i go ostaiv na 0 sila ! spazi go toa 0 sila 
i se 4udam 0 sila i vikam sigurno sam ga utepal ! ojde na drogata pisuva 0 ubieni mafijasi
odam pa ga napagam pisuva 5 pati napadnat u 1 cas !! KAKO MOZE NA 0 SILA DA GO OSTAVAM? pisuva Energija 0% !!! Te molam stavi mi go kako ubien mafijas ! oti ne e fer!

**Comment by deadwalker** [comment]
pa neznam do sto e i kaj mene se pojavi toa na nula i pisuva oti e napadnat 5 pati

**Comment by VIGI** [comment]
koga e u 0 trepa da pocekass eden cas i treba pak da se napadna prviot sto go faca go ubiva

**Comment by TNR** [comment]
trebale su da gu testirav prvo :/
