### ISSUE TITLE
Otvorete i pomognete dokolku sakate  !

### ISSUE THREAD

**Issue by stefan123** [skechboy/MAFIA#214]
Kako mozham da si go zgolemuvam brojot na Ubijci bez trkalo na srekata i posetuvajne na mojot taen link i kako mozham najdobro da ja zgolemam mokta ?
-blagodaram odnapred

**Comment by Filipwnr** [comment]
ODI na mojot http://www.mafia.mk/profile/2127 pritisni pokazi pocit i ja ke ti kliknam na tajniot link ;)
