### ISSUE TITLE
OFFLINE

### ISSUE THREAD

**Issue by mafiapronewacc** [skechboy/MAFIA#216]
admine gledaj sto se desava moj e acc ama ne si go znam pass na stariot acc na github ovde gledaj sea jas sum online na mafia a coveceto mi go dava offline eve ti primer slika http://pic.mk/images/offline.jpg

**Comment by KP3T3H** [comment]
му треба време да се обнови да стане онлајн

**Comment by mafiapronewacc** [comment]
hahaha

**Comment by barcellona** [comment]
На секои пет минути се обновува....:))
