### ISSUE TITLE
Швајцарска Банка Грешка

### ISSUE THREAD

**Issue by riba** [skechboy/MAFIA#219]
Како што знам 2% камата на 5М се 100 000 пред 00:00 ставив 5М после имам 5 001 250 значи 1250 камата ми даде така треба да биде или грешка е ?

**Comment by KP3T3H** [comment]
каматата се пресметува редовно, на секој саат, т.е. во 01:00, па во 02:00, 03:00,. итн..

**Comment by deadwalker** [comment]
stvarno na sekoj cas?

**Comment by riba** [comment]
Аммм ахам

**Comment by riba** [comment]
Еми ако пресметува по 1250 на секој час. 5 М да ставам и 24 часа да пресметува по 1250 тоа се  30 000. А на 5 М , 2% камата се 100 000. ова не ми е јасно

**Comment by KP3T3H** [comment]
првиот час ти дал 1250, после на 5.001.250 ќе се пресмета камата, и се така секој час

**Comment by riba** [comment]
А од кај тие 1250 ? кога пишува 2 % камата ?

**Comment by KP3T3H** [comment]
2% камата е за 24 часа, односно на 5М е 100К камата, 

ако ме прашаш дали ми се свиѓа системот како стигнува камата, ќе речам НЕ. најубаво е на секои 24 часа за да знам колку точно ќе добијам... 

ако не друго барем можеле да го стават стариот систем само на швајцарска банка, дека ако и на народна банка се стави на секои 24 часа да стигнува камата, сите поголемиот дел од парите ќе го чуваат во сеф и во 01:00 часот ќе ја земат каматата и пак назад во сеф

**Comment by riba** [comment]
Ахам. Они нека стават на секој час распоредено да иде каматата ама зборот ми е кога ќе ги собереш сите тие пари што треба по 1 час да ги дават излегува 30 000! А за 24 часа 2% камата е 100К што значи тоа им е грешка. Значи ако решиле таа камата од 24 часа да ја разредат на секој час излегува по 4166 на секој час да праќат. А они праќат по 1250.
