### ISSUE TITLE
Проблем со IP адресите при регистрација

### ISSUE THREAD

**Issue by Pipelin** [skechboy/MAFIA#22]
Разговаравме дека во гостивар кабелскиот оператор Мултимедиа има 2 IP адреси кои се менуваат често, да не речам на секои 5-10 минути. Во случајов со иста IP адреса сме регистрирани јас Pipelin и уште еден играч SiniMC. Пробуваше мојот пријател (комшија) кој има иста IP адреса да си направи профил и му се појавува овој проблем како на сликава: http://pic.mk/images/11292438373.png  .
Предлагам за IP адресите кои ќе ти ги пратам на мафиа по ПП да има повеќе од 2 регистрации затоа што ова ќе им се случува на сите кои имаат исти интернет како мојот.

**Comment by skechboy** [comment]
И покрај тоа што има голема можност ова да се злоупотреби :) решивме да дадеме повеќе дозволи на посочените ип-адреси

**Comment by Pipelin** [comment]
yey сега да направам мулти :) хех
