### ISSUE TITLE
БЕЛЕЖНИК

### ISSUE THREAD

**Issue by KP3T3H** [skechboy/MAFIA#221]
предлагам да има бележник во менито "ПРОФИЛ" каде што ќе може секој мафијаш да запише разни работи, како на пример: за колку го купил алкохолот, за да знае на која цена да го продаде, некои важни пораки, и ред други работи што на мафијашот би му биле од корист... 

еве лимитот на карактери нека биде ограничен, т.е. да биде околу 2.000 (може и помалку но што повеќе подобро :)

**Comment by xBOJANx** [comment]
ne e loso amo nema sansi da se prifane
pozdrav

**Comment by Filipwnr** [comment]
Jas sum za dosta e dobar predlogot na primer koga imas za ubivanje mafiajsi linkovik da  si stais tamu mozes

**Comment by njkhooihjho** [comment]
interesno moze da se naprave vakvo nesto (sekako ako na adminot mu se dopadne)

**Comment by deadwalker** [comment]
da toa go ima na bandias.com

**Comment by KP3T3H** [comment]
незнам дали таму го има или не, ама според мене треба да го има.
