### ISSUE TITLE
Чекам што побрзо одговор!

### ISSUE THREAD

**Issue by riba** [skechboy/MAFIA#223]
Хакни ја веб страницата на МВР ми е 30% шанса да успееш
Bugatti Veyron ми е 14% шанса за да успееш

Сакам да кажам 2 дена веќе ми се така а 24/7 сум на неа и не се подмрднуваат % МВР на 30% а бугатти на 14% и сега сакам да прашам дали ќе се накачуваат уште или така ќе останат ?

**Comment by Filipwnr** [comment]
i mene isto...

**Comment by riba** [comment]
ЛЕлелеле ебати играва :@

**Comment by KP3T3H** [comment]
dobro e sto ne se namaluvaat, odi poigraj malce na bandias.com procentite se namaluvaat

**Comment by riba** [comment]
Абе се е ОК али за жал јас играм на MAFIA.MK ! И чекам одговор на прашањето што го поставив.
