### ISSUE TITLE
AJ NEKOJ NEKA MI KAZE WE!!

### ISSUE THREAD

**Issue by Kradec** [skechboy/MAFIA#224]
kolku maximun sila moze da se zeme od 5 napadi????????????????????

**Comment by deadwalker** [comment]
15

**Comment by Kradec** [comment]
zna4i taka? eden bese na 18 sila i mu ja zedoa za 1 4as be!!! :@ vikam aj ke po4ekam use 1  4as ke bide nakaj 8-7 a oni ga utepale 18 sila imase

**Comment by Kradec** [comment]
EJ KOJ KE ODGOVORE B E ??
