### ISSUE TITLE
zasto e ova vaka?:S 

### ISSUE THREAD

**Issue by flexMK** [skechboy/MAFIA#225]
mn e glupavo ova napraveno jas ako sum potrcko nemozam da go napagjam toj sho e graganin pa daj ke bideme graganin site za da mozeme da gi tepame poslabite za da nakacuvame drogata ic ne e okey toa mislam deka treba da mozeme da gi napagame site a na samo ti sho se nash rank.. posho em treba sea grad da barame em rank da barame em mok ednakva vishe nema smislaa :)

**Comment by njkhooihjho** [comment]
i da sI graganin pak ke nemozes da go napadnes toj so e graganin MOZES DA NAPAJGAS MAFIAS KOI SE SO POGOLEM RANK OD POTRCKO (TO EST DA BIDI ЏЕБЏИЈА ) BEZ RAZLIKA NA MOJK!!! SEGA  SAVATI KAKO ODAT RABOTITE????:)

**Comment by flexMK** [comment]
ajde be i sho ke gi barame samo dzebdzi ti sho se da gi tepame bogdacuva i da brani gluposti u boja porano sho ubavo moesh site da si gi tepame 
sea... sranje u boja

**Comment by njkhooihjho** [comment]
i tie so se nad rank џебџија
