### ISSUE TITLE
Печатна грешка со Швајцарската банка

### ISSUE THREAD

**Issue by 7sidedDice** [skechboy/MAFIA#226]
Ова не е нешто многу големо, но ако напишете нешто во полето кај Швајцарската банка што не е број, ќе ви каже „Внеси невалиден број!“ а треба да биде „внесе“.

**Comment by njkhooihjho** [comment]
mala greska

**Comment by riba** [comment]
Не е баш мала од Внеси до внесе има голема разлика. Ај свати ја ти ова Внеси невалиден број ?!

**Comment by klikstermkd** [comment]
"Внеси" значи во моментот да внесиш, а "внесе" ти кажува дека претходно си внесол (минато).

**Comment by npoptomov** [comment]
:)))

**Comment by skechboy** [comment]
Проблемот е решен. Ви благодарам за известувањето.
