### ISSUE TITLE
АЛОООООООООООООО !!!

### ISSUE THREAD

**Issue by riba** [skechboy/MAFIA#227]
ШТО Е ОВА БЕ? КАКВА МАФИА Е ВААА БЕЕЕЕЕЕ ??? ВО ЖИВОТ ДА УКРАДАМ КОЛА СИГУРНО ТОЛКО ШТЕТА НЕМА ДА НАПРАВАМ !!!!!!! КОЛКО ПОВЕЌЕ ИСКУСТВО ИМАМ ТОЛКО ПОВЕЌЕ ШТЕТА ИМАМ БУГАТТИ 40% ШТЕТА ШТО Е ОВА БЕ ДАЈТЕ МИ ОДГОВОР ОДМА !!! ГЛУПАВИ ГРЕШКИ/БАГОВИ ИМАТЕ

**Comment by deadwalker** [comment]
epa kolku si povisok rang tolku e potesko

**Comment by riba** [comment]
@deadwalker ај прочитај што напиша и не тропкај глупости без врска

**Comment by prokiller2** [comment]
@deadwalker во правоси  те подрзувам

**Comment by riba** [comment]
Абе што се правите ПРОСТАЦИ како може поголем ранг толку потешко ти кога ке пробуваш нешто да украдеш во приватен живот најпрво кога ќе пробаш ќе направиш голема штета првиш првиот пат кога ке пробиш или последниот ? Простак еден

**Comment by KP3T3H** [comment]
намерно е направено така, за да се игра со помалку пари, инаку ако го украдеш бугатито со минимална штета (1-5%) кога ќе го продадеш добиваш над 1 милион евра , вака добиваш половина околу 600.000

**Comment by riba** [comment]
Ми незнам дека бев читал прашуваа зошто е тоа ШТЕТА да биле колите без штета! И админот одговара вели вике ако украдеш кола вике треба сигурно прозорец да скапиш да скинеш жичка за да ја запалиш итн. и ајде нека размислат малце колку повеќе пробуваш да ја украдеш толко повеќе искуство добиваш и помалце штета да правиш а они обратно прават колку повеќе искуство толко повеќе штета дај размислете за ова измислете инаку да биде инаку сега како што е нема смисла

**Comment by npoptomov** [comment]
abe riba nema vrska rangot so shtetata ... kolku steta ti se padne tolku ... toa e cista sreka

**Comment by riba** [comment]
nema vrska od prav zdrav mozok nemoj glup da me pravis se sekavas koga po4na da ja igras kolku steta imase 4-5% taka ? taka e sigurno. Kolku iskustvo imase po4na od 0 do 2000 iskustvo 5-6 % steta imase jas imam 36 iladi iskustvo imam 40% steta i sto e rabotata. Ako ne e drogata na cisto ke propadnam od bugatti

**Comment by npoptomov** [comment]
hahaha koga si pocnal da ja igras 4-5% sii imal steta na bugati ?????

hahaha pa normalno deka na pojaka kola ke napravis poveke steta ti koa si pocnal sigunro ne si kradel bugati so 3-4 steta

**Comment by riba** [comment]
ne sum kradel ama vo privaten zhivot ete nema vrska koga ke po4nis najjaka kola da kradis i se taka ja kradis i potoa povekje steta ke pravis ? ili veke koga imas iskustvo so pomalce steta ke kradis ?
