### ISSUE TITLE
Убиени мафијаши

### ISSUE THREAD

**Issue by riba** [skechboy/MAFIA#229]
Незнам како што да ви ја ставам дали како предлог или како голема грешка ! На што личи ова на пример некој немат ни ту еднаш ја појачено дрогата а им е FULL. Сакат да убиваат мафијаши но неможат! Зошто ? Ќе го наѓаат цел ден ќе дое istrel (така како пример) ќе го убие. На што личи ова значи на некој ни ту 1 пат(и) не му е појачена дрогата а на некој 5 пат(и) и што ќе кажете вие за тоа??? На мене ми е 2 пат(и) дрогата и полесно убивав тогаш отколку сега ! Еднаш рефреш давам на страницата побавен ми е нетот и почивај во мир итн. ми излегува. И кога ќе видам кој го убил пак некој од топ5 листата на убиени мафијаши. Значи да има ред ако веке 2 пат(и) ти е појачена дрога додека не ја наполниш цела FULL до таму каде што ти е отклучено да не бива да убиваш мафијаши. ОД кога ќе ја наполниш до таму каде што ти е отклучена пак да можеш да убиваш е тогаш ќе има ред и дур тогаш и тие што им е фулл а ни ту еднаш не им е надградена и тие тогаш ќе можат да ја надградат. А не сега мене ми е 2 пат(и) за 1-2 недели ќе ја наполнам а 1-2 недели се мачам 1 барем да убијам но неможат мислам дај средете не бива ова вака :@:@:@:@

**Comment by njkhooihjho** [comment]
da vo pravo si treba ova da se sredi :)

**Comment by riba** [comment]
Па преку к*р више нека направат како што напишав да можеме да живнеме малку.

**Comment by DonMaster** [comment]
ako istrel ili  bilo koj e sposoben da naprai nad 15 kills,togas zosto vie ne ste sposobni???samo kritikuvate nekogo bez vrska -.-

**Comment by riba** [comment]
Слушај што ќе ти кажам не е до способноста сите немат ист интернет. Значи сите користат различен интернет (побрз побавен) и сега јас додека дадам рефреш ќе го убијат и кога ќе видам од кој гледам пак некој од листата на топ5 играчи на убиени мафијаши.

**Comment by njkhooihjho** [comment]
da barem neka se napraj po staro [od na beta] so petpati  poslab od tebe da mozes da napajgas

**Comment by riba** [comment]
Да и таа е добра идеја.

**Comment by DonMaster** [comment]
na betata se bunevte deka necini 5 pati poslab,ova-ona...sea da go vratat toa :/ 
stv ne vi se naoga kraj

**Comment by npoptomov** [comment]
riba ne se buntuvaj nogu i ti neznaes sho zbores ! pa koga veke gledas deka ti gi zimat ubistvata ti nema da go cedis od 100% ke pocnes da baras eden po eden od listata na mafijasi ke najdes na 20-30 i ke go ubies ! 
i dobro e toa sho moze da se napagaat site mafijasi ... bidejki na pr. vo vistinskata mafija ke ispadne deka najakiot mafijas nemoze da go ubie najslabiot...

a bi bilo dobro da se regulira toa so napadite... na pr. ako mu iscedes poveke od 50% entergija toj da bide kako kidnapiran od tebe i nikoj da nemoze da go ubie drug...i ako se ukluci da ti dade pari ili nesto za da ne go ubies...

**Comment by riba** [comment]
slusaj nesto znachi sega ne e problem za mene za mene e najmalce no ke gi napram uste 5 kills no ima nekoj sto imaa baven internet i koga ke napadnat na 02 stranicata za napadni im ja otvara na 07 a mafijasot e veke mrtov.  I druga greska ja na primer ti zimas nekoj od 100 na 10 go donesuvas i drug da ti go ubie ke bides lut ? Ne li bi bilo dobro da stavat koj najmnogu go napagal toj da go ubie.Inaku ne te razbrav za podolu dali sakase da kazhes da se ubivaat site mafijasi (graganin , pottrcko) za toa sum ne bidejki ima nekoj kreiraat useri za samo da si pravat kills ili pocit pa taka uste graganin da mozes da ubivas i ..  .kade e krajta.

**Comment by npoptomov** [comment]
veleam deka za mokta e dobro da moze da se napaga sekoj...a ova so rangovite ne e problem skoro site ke go nadminat potrcko.... 

nego sakam da kazam da se regulirat napadite ako go iscedes poveke od 50% da bide kidnapiran od tebbe i drug da nemoze da go napaga

**Comment by riba** [comment]
ete i taka moze stom ke go doneses do 50% no edno ke ne buni i drug moze pak isto da go napaga zaedno da go donesete do 50% najdobro mislam deka ke bide i interesno ke bide koj najmnogu go napagat toj da go ubie

**Comment by KP3T3H** [comment]
па тоа и томов кажува, кој ќе земе 50% на еден мафијаш да може само тој да продолжи да го напаѓа, а не до 50% кој прв ќе го донесе. оти ти можеш да почнеш да напаѓаш некого и од 80%,

**Comment by riba** [comment]
Како и дае како што е во моментов многу е глупо направено.

**Comment by VIGI** [comment]
riba ic ne go nosi ponataumo mnogu glupavo e kako i da e nekako treba da go namestat mene mnogu mi trebat barem edno dve da gi praem nikako ako bi bilo koj povise ja bi pocnal od 100 so nekoj i ce znam deka e moj

**Comment by ChillmaxTM** [comment]
koga ke go stavis na 50% sila da go kidnapiras i kolku sakas da go napagas, a ne ti pisuva go napadna 5 pati vo posledniot cas

**Comment by ChillmaxTM** [comment]
sinoka eden tepav do 00:00 casot imase 0% sila ide a1emdar i mi go zima ubistvoto, a imase 40 000 000 evra jas se slozuvam so riba i npoptomov

**Comment by riba** [comment]
хмм VIGI сакаше да кажеш ако му земеме 50% и веќе се знае дека е наш и велиш така ке има многу убиства е не е баш така ти се зголемува времето за чекање за повторно да напаѓаш и за еден ден тешко работа да намалиш 3јца на 50% и да ги убиеш.

**Comment by JackDaniel** [comment]
se soglasuvam so riba  , vcera napagav dvajca cel den  i istrel mi gi zema @@@@
Napravete da bide koj najveke go napadnal toj go zema , a ne vaka 50 pati go napagas 
a nekoj so 1 napad ke ti go zeme !!!  _POPRAVETE GO OVA VEDNAS_ 
i stajte nekoja Misija da izvrsime kako beta mafia pronajdi go zlatnoto jajce ^^
