### ISSUE TITLE
Проблем со процентите на рангот

### ISSUE THREAD

**Issue by Pipelin** [skechboy/MAFIA#23]
Забележав кај еден играч проблем според мене кај процентот кај рангот 
Слика: http://pic.mk/images/mafiam1292443621.png
Џепчија - 3.499999999999 % 
Малце е глупо зашто да ги има онолку деветки. Дали може да се среди ова ?

**Comment by skechboy** [comment]
Не е пронајдено (404)

The server can not find the requested page :)

**Comment by Pipelin** [comment]
http://pic.mk/images/mafiam1292447562.png кај овој член го видов истото сега исто.

**Comment by DeadBoss** [comment]
Скеч то се појаве поради оние %20%20 на крајо делитниги и ентер ! :)
