### ISSUE TITLE
Skech ...

### ISSUE THREAD

**Issue by DoubleL** [skechboy/MAFIA#230]
Другар абе дај објасни ми... Што е работава со Expirenceto??
Пример сум Поттрчко и сум 20.50 % ... И сега извршувам најтешко злосторство најтешка работа и пробувам да украдам најјака кола... и после тоа би требало да имам некаде околу 21 и нешто % .. Но понекогаш останувам повторно на истото... И морам да се re-logiram и пак да извршам злосторство кражба на кола и работа за да се крене ... А понекогаш и ми го враќа назад Expirenceto... Исто така имам приметено и дека потешко се крева... Дали вие го направивте тоа или мене така ми се чини? ... Дали алкохолот се произведува на секој 1 час ? ... И ако можеш да ми ги кажеш командите како се пишува во боја... и некој други освен тие што веке ги пишува во Лична Порака :) .   Фала Однапред.

**Comment by Hellmafiamk** [comment]
на секој левел е потешко дигањетo "екпириенс", алхохолот може да се продаде само во друга држава, пр ако си купил у македонија(било кој град) треба да идеш у друга држава, пр бугарија и таму да ја продадеш

**Comment by DoubleL** [comment]
Веке знам дека потешко се крева exp. на секој левел... Но дали сварно има БАГ или не ? Пошто јас убаво објаснав горе што е работата :)
