### ISSUE TITLE
greska koga klavam klip od youtube go dava belo vo mojot profil

### ISSUE THREAD

**Issue by LjubeGVG** [skechboy/MAFIA#233]

**Comment by LjubeGVG** [comment]
imam videno i na drugi taka da im e pravam kako sto pisuva tamu

**Comment by DoubleL** [comment]
Пример сакаш овој линк да го ставеш: http://www.youtube.com/watch?v=iLkrZygzrw8

Не го ставај цело ... 
Туку [youtube]iLkrZygzrw8[/youtube] ... 
Без тоа HTTP://www.youtube.com/watch...... 
Се надевам дека помогнав :)

**Comment by LjubeGVG** [comment]
fala mnogu mi pomgna jas go klavax cel link
