### ISSUE TITLE
Предлог

### ISSUE THREAD

**Issue by BAD-BOY** [skechboy/MAFIA#238]
Дали може да се направи да не се крадат мафијаши ??? ocekuvam odgovor

**Comment by njkhooihjho** [comment]
da ne se kradat?

**Comment by KP3T3H** [comment]
да не ги гагнуват мафијашите што се на малку здравје
пример ти тепаш некој мафијаш од 100 здравје и на крај друг ќе го утепа

да нема гагнување, тоа сака да каже

**Comment by njkhooihjho** [comment]
da treb toa da se napravi

**Comment by VIGI** [comment]
nekako treba da se namesti i ja samo gledam u kraj koga ce stigne idem ako go pobedim ok a na pr da ima nekakov red ja bi utepal 5,6 casa nekoj ama u kraj da znam deka e moj

mislam tesko deka ce se namesti nesto tuka..... ova znaci sreca koj ima negov e

**Comment by riba** [comment]
Не е до среќата ти ако имаш некој на 1% и уште 20 мафијаши го имат истиот а ти си го донесол до толку и ќе успее оној што има најбрз интернет што значи многу е глупо така

**Comment by Hulk** [comment]
да вистина е глупо така јас го тепав играчот Filip_boom и го оставив на 2 проценти и требаше да чекам 1 час и таман стигна да го нападнам некој пред нос ми го зема.Не е фер

**Comment by njkhooihjho** [comment]
riba se buni ama izgleda nego mu e ubo mi ima zemeno 2-3 mafiasi

**Comment by riba** [comment]
Сигурен си дека имам земено 2-3 или 33 ? :) Колко и да ми е бавен нетот се трудам :)
