### ISSUE TITLE
Проблем во таен линк

### ISSUE THREAD

**Issue by DamDav159** [skechboy/MAFIA#24]
Кога ке стиснам ми пишува "Твојата апликација за платен убиец беше регистрирана." ве молам поправете ми го ова.Гледам не сум единстевн со овој проблем.Чекам новости.

**Comment by skechboy** [comment]
Тоа е нормалната порака која се појавува кога ќе кликнеш на нечиј таен линк :) не гледаме никаква грешка тука...

**Comment by DamDav159** [comment]
да но истата грешка ја има пофторено и некој друг
