### ISSUE TITLE
Фамилија

### ISSUE THREAD

**Issue by prokiller2** [skechboy/MAFIA#240]
Луге оти не правите фамилија :( напрајте дај кажете .

**Comment by KP3T3H** [comment]
стигни ранг 100% кум и напрај фамилија

**Comment by prokiller2** [comment]
па коа ке стигнам ке направам но има време до тоа :)

**Comment by njkhooihjho** [comment]
ne e to so rank kum 100% tuku ima problem za to familija ne se pravi treba adminite da go resat problemot inace kum 100% se Vito,dexter69 i mn. drugi

**Comment by prokiller2** [comment]
ima problem :( igrava e problem cela :D

**Comment by riba** [comment]
Хахах камо да е само тоа грешка името и е грешка на играва :D

**Comment by prokiller2** [comment]
oti ?
