### ISSUE TITLE
Предлог!!!!!ВИДИ СКЕЧ!!!!

### ISSUE THREAD

**Issue by njkhooihjho** [skechboy/MAFIA#241]
Двам предлог да се направи да можи по лична порака да се праќаат линкови.Чекам одговор Skechboy

**Comment by npoptomov** [comment]
тоа неможе од безбедносни причини видејки има многу играчи што праќаат разни линкови за фишинг сајтови со кои ги крадат лозинките на играчите!

**Comment by njkhooihjho** [comment]
ok
