### ISSUE TITLE
GRESKA VO KOMENTARITE!!!

### ISSUE THREAD

**Issue by DonMaster** [skechboy/MAFIA#245]
koga ke razgleduvas komentari kaj nekogo koj ima poveke strani so komentari,i na pr ke kliknes na 5 strana,koga ke se vratis na tvojot profil da gi procits tvoite komentari,prazno e...treba da go popravite sekogas da se vraka na prva strana ;)

**Comment by KP3T3H** [comment]
исто е и ако има повеќе страни пример 3 одиш на третата, и кога пак ќе ги отвориш будни мафијаши те дава на третата страна наместо на првата
