### ISSUE TITLE
Adminiiiiiiiiiiiiiiiiiiiiiiiiiiiii !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by woralck** [skechboy/MAFIA#248]
Zosto ne mozam da  koristam kredit ?????????????????????????????????????????????

**Comment by riba** [comment]
Како што разбрав. Кредитите ќе се користат за понатаму кога "ќе го решат проблемот" . И ќе се купувало нешто што ќе неможе да се купи со пари.
