### ISSUE TITLE
ADMINIIII POMOSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS

### ISSUE THREAD

**Issue by woralck** [skechboy/MAFIA#249]
Kako mozam da stavam nov paswprda stariot go zaboraviv ???????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????

**Comment by npoptomov** [comment]
na vleznata strana na mafia.mk imas opcija ''zaboravena lozinka'' ...tamu ke kliknes i ke ti ja pratat novata na emailot
