### ISSUE TITLE
Предлог

### ISSUE THREAD

**Issue by woralck** [skechboy/MAFIA#250]
Да мозет да се патува во другите дрзави со кола.Да бида побрзо но поскапо....................
Размислете

**Comment by riba** [comment]
Јас би дадол предлог од град на град да има освен Железнича и Автобуска да има со Taxi тоа да биде на 15 минути и да биде 3 пати поскапо од автобуската. И друго ако веќе има Тахи да можеш да си местиш време за колко време сакаш да стигнеш т.с. да си регулираш со стрелки да има < 15 мин > и на пример да кликнуваш на левата еднаш за 14 мин и така да се зголемуваат парите тоа вие ќе си одредите.Да биде многу поскапо

**Comment by woralck** [comment]
dobra idea e
