### ISSUE TITLE
?

### ISSUE THREAD

**Issue by AlekTheKid** [skechboy/MAFIA#251]
ејјј ја сум џепџија и сеа нели се одворени колите од брза класа пробувам да украдам Alfa Romeo Brera и ми вика  Грешка !!!!!немаш доволно искуство да ја украдеш колата а одворена ми е :@ што е овоа ?

**Comment by deadwalker** [comment]
па накачи искуство

**Comment by AlekTheKid** [comment]
da be ali od ti go otvara a posle edno nivo ti dava da krades
