### ISSUE TITLE
Предлог - Напади

### ISSUE THREAD

**Issue by npoptomov** [skechboy/MAFIA#252]
Мислам дека многу играчи имаат проблем со убивањето на мафијашите...Мислам дека би било добро доколку некој веќе напаѓа мафијаш да биде сигурен дека после толку и толку време ќе го убие... На пр. може да се стави вака:
Доколку играчот му одземе сам повеќе од 50% од здравјето автоматски тој мафијаш да биде под негова контрола како да е киднапиран од него...И ако сака некој друг да го нападне да пишува ГРЕШКА!!! Играчот е киднапиран или така нешто... И доколку играчот се уклучи во тоа време да има можност тој што го киднапирал да го пушти но да се спогодат т.е да му извади пари во кеш да му даде итн...

Поздрав!

**Comment by deadwalker** [comment]
Предлогот е Супер иначе некој има х5 или повеке а некој неможи еднаш да си ја дуплира

**Comment by riba** [comment]
@npoptomov еве и ти дојде за предлог за убиени мафијаши. Значи не е целта кој може да убие и јас би можел да убијам 100 и ти и многу други додека на 5-6 не кикснат но потоа ке им стане јасно дека се сака добар ИНТЕРНЕТ. Потполно се согласувам со предлогот. Но за жал нема админи.

**Comment by sakas** [comment]
brat mn dobar predlog i jas se soglasuvam jas bev napagal eden i togas koga bese momentot da go ubijam mi go ubia daj koga go napagas i mu zemes 50% energija tvoj e.Neka se resi ovaa

**Comment by slavemkd** [comment]
I jas se soglasuvam dobar predlog!

**Comment by mustrak** [comment]
ednas i jas sakav da go napadnam na eden mafijas i go ostaviv na 3 energija,i mi napisa za eden cas da se obidam,i pomina eden cas i so da vidam ubien.mnogu dobar predlog e ova,i baram od adminite koi gi nema da se usvoi
