### ISSUE TITLE
Проблем со полињата за здравје и ранг.

### ISSUE THREAD

**Issue by DonMaster** [skechboy/MAFIA#256]
koga vo banka imas nad 100.000.000 evra,polinjata za zdravje i rang ne se na svoja pozicija,treba da se iscentriraat ;)

**Comment by deadwalker** [comment]
да или кога си во Санкт Петербург и таму не се центрирани

**Comment by DonMaster** [comment]
hah a koa si u ST.Peterburg i imas 100m u banka,epten se izlezeni od pozicija xD

**Comment by deadwalker** [comment]
хахах :D
