### ISSUE TITLE
ПРЕДЛОГ ЗА АЛКОХОЛОТ

### ISSUE THREAD

**Issue by Vampire2** [skechboy/MAFIA#258]
ДАЛИ МОЖЕ АЛКОХОЛОТ ДА ГО НАПРАВИТЕ КАКО ДРОГАТА.КОГА ЌЕ КУПИШ НЕКОЈ КИЛОГРАМ И АКО ГО ПРОДАДЕШ ДРУГИОТ ДЕН ПАК ДА ГИ ИМАШ КИЛОГРАМИТЕ.ПОЗДРАВ!

**Comment by KP3T3H** [comment]
ти не произведуваш алкохол, да имаше некоја фабрика ќе може вака НЕ

**Comment by ChillmaxTM** [comment]
Остави го тој целиот се спурил.:D:D:D:D
