### ISSUE TITLE
Поправка

### ISSUE THREAD

**Issue by DeadBoss** [skechboy/MAFIA#26]
Во кеш имав 700€ пробав да поправам еден автомобил и го поправив а ми вели поправката чинеше 1.800€ 
Дали зема пари од банка или се работи за грешка незнам !
Видете админи ! :)

**Comment by skechboy** [comment]
Парите за поправка ги зема од банката. Сепак ти благодариме за известувањето.

**Comment by DeadBoss** [comment]
Незнаев набрзина прицнав и видов !
