### ISSUE TITLE
PREDLOG!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by TNR** [skechboy/MAFIA#268]
MOZE KARTATA DA SE NAMALI ZASTO IMA MNOGU PATUVANJE, A MOZE I DA NE SE NAMALI KARTATA NO CENITE DA SE NAMALAT, ZASTO STVARNO OVAA MAFIA SEZONA 2 ISTA E KAKO MAFIA II  I TAMU NEMOZES DA IMAS MNOGU PARI I OVDEKA I SPORO NAPREDUES NE E KAKO VO SEZONA 1 EDEN RANG KACIS ZA ED'N D'N

**Comment by deadwalker** [comment]
pa igrava e napraena so pomalce pari da se igra potesko da se naprednuva

**Comment by riba** [comment]
Точно. За 1 месец активно играње можеш да напредиш. Намерно е направено вака да се игра со помалку пари да се намали вредноста на парите. Инаку за 1 месец активно играње можеш со над 50 М дневно да располагаш.

**Comment by deadwalker** [comment]
koga ke napolnis na kraj drogata mn poveke se isplaka na starata so se veli so x10 ili poveke edvaj 300 milioni ke soberis sea so x3 ke soberis tolku
