### ISSUE TITLE
Регистрација - ИТНО

### ISSUE THREAD

**Issue by DeadBoss** [skechboy/MAFIA#27]
Копчето за регистрација не работи на почетната !
некои знаат за /register ама другите 
Итно попрајте го !

**Comment by skechboy** [comment]
Хмм кај повеќето што проверив е ОК. Каков прелистувач користиш и на кој ОС си ?

**Comment by SMacedonia** [comment]
Кај мене работи.

**Comment by DeadBoss** [comment]
Google Chrome 
Windows 7 
Ова го користам :)
