### ISSUE TITLE
МАЛА ГРЕШКА ВО "Информации"

### ISSUE THREAD

**Issue by Wizardx** [skechboy/MAFIA#274]
Во Мојот Профил/Лична Порака = каде што пиши 

"Забелешка: Можеш да додаваш линкови, слики и видеа со: [url]твојот линк[/url], [img]твојот линк[/img] и [youtube]твојот линк[/youtube]" 

пиши за линк "[url]твојот линк[/url]", а треба [url=твојот линк]Текст[/url]

**Comment by KP3T3H** [comment]
toa sto ti go kazuvas e ako sakas nekoj tekst da go naprais link
a kako sto e primerot daden e samo link i cel link ke se gleda
[url]mafia.mk[/url]

[url=mafia.mk]mafia pocetna[/url]

i dvete pravat isto ama razlicno se napisani :):)
