### ISSUE TITLE
ZMK 

### ISSUE THREAD

**Issue by AlekTheKid** [skechboy/MAFIA#275]
zimi kurov da ti se pluknam na mafijata .. Ilija8 imase vrednost ako go ubiam 2m plus ne mi gi dae ako ajde sea pa na pavelkolev 2m ne mi gi dae so voa zimi kurov 4m ne se malce

**Comment by DonMaster** [comment]
ahahhaaha 4m ne se malce vikas...da ne se mnogu slucajno? xD
