### ISSUE TITLE
Нови Градови

### ISSUE THREAD

**Issue by SMacedonia** [skechboy/MAFIA#28]
Зошто ги нема другите градови во делот за патување? Дали тоа значи дека џабе фрлив 300.000 за градот Катана? :)

**Comment by skechboy** [comment]
Значи со воз и автобус се патува низ градовите во една држава, а помеѓу државите се патува со авион :)

**Comment by DeadBoss** [comment]
А ке се купуват и аеродроми или ?

**Comment by skechboy** [comment]
Да да провери во Лицитации од десното мени,

**Comment by Pipelin** [comment]
Па ги има Аеродромот и таму автобуската некаде 800 илјади беше едното идете лицитирајте :)

**Comment by DeadBoss** [comment]
Знам за еднио ама за другите 
сакав да знам шо е работата

**Comment by DeadBoss** [comment]
Ти скеч тука пишиш инбокс не ми вракаш сс

**Comment by DeadBoss** [comment]
Упс грешка мислев инбокс ти пратив :/ сру
