### ISSUE TITLE
ГОЛЕМА ГРЕШКА СО НАПАЃАЊЕ!

### ISSUE THREAD

**Issue by Wizardx** [skechboy/MAFIA#282]
Напагам мафијаш ранг гангстер а јас сум макро и излегва мафијашот е премногу слаб, треба да биде барем 2 ранга под тебе! xD како можи ова вака кога  е поголем ранг од мене и гледај после шо ми излезе : "Сте го погрешиле градот" а двајцата сме во Скопје 2 пати го проверив градот! Средете го проблемот што можите побрзо.

**Comment by skechboy** [comment]
Работиме на одстранување на проблемот.

**Comment by Wizardx** [comment]
Најдобро е да направите така да не можи да се напаѓат тие шо се 2 ранга послаби

**Comment by skechboy** [comment]
Проблемот е решен, сега можете да напаѓате играчи што се само 5 ранга под вас.
