### ISSUE TITLE
Зашто неможам да напаѓам мафијаши

### ISSUE THREAD

**Issue by Slavco16** [skechboy/MAFIA#285]
КОга ке нападнам некој поголем ранк од мене во ист град ми пишува :
Во обидот да се самоубиеш пиштолот ти се блокира .
Не ти било пишано да умреш денеска

**Comment by skechboy** [comment]
го испитуваме овој проблем ти благодарам за известувањето.

**Comment by Slavco16** [comment]
и сакам да може и со граѓанин да нападнам некој ако сум ранк граѓанин
