### ISSUE TITLE
Неможам да убијам мафијаш!

### ISSUE THREAD

**Issue by Slavco16** [skechboy/MAFIA#286]
Имам 100 поени за напад помал ранк сум од него  во ист град сме но ми пишува дека сум сакал да се самоубијам xD @:

**Comment by BoCkO-99** [comment]
и мене исто незнам што му стана!

**Comment by olegz1** [comment]
Тоа е така затоашто е помокен од тебе. Или пак можда ти повеке мок имаш од него ама можда он има повеке платени убијци или пак поени повеке.
