### ISSUE TITLE
Затвор - Предлог

### ISSUE THREAD

**Issue by SMacedonia** [skechboy/MAFIA#29]
```
Пресуда: 00:00:40
Кауција: 10.620  €  
```

Како истекува времето така и да се намалува цената за кауција, односно да не мора да се претиснува на рефреш автоматски да покажува како што и времето се намалува.

И да може да платите за ослободување од затвор преку парите што се во Банка. :)

**Comment by skechboy** [comment]
Се е можно но намерно ни е направено така затоа што ќе се изгуби смислата на кешот :) Инак околу вредноста на кауцијата би требало така да биди но нешто има некоја грешка ти благодарам за известувањето ќе ја одстранеме грешката во најбрзо време.
