### ISSUE TITLE
Не можам да напаѓам други

### ISSUE THREAD

**Issue by BoCkO-99** [skechboy/MAFIA#290]
Кога ќе нападнам некој ми пишува:
ГРЕШКА!!!
Во обидот да се самоубиеш пиштолот блокира.
Не ти било пишано да умреш денес.
Ги исполнувам сите услови(на пример напаѓам џепчија со помалку моќ во ист град сме и истото го пишува,а јас сум инаку поттрчко).Ова ми го пишува на се што ќе нападнам без разлика на условите.

**Comment by som1** [comment]
treba da bidis nada rang pottrcko za da napagas drugi
