### ISSUE TITLE
greska so poka4uvanje na mok na familija

### ISSUE THREAD

**Issue by deadwalker** [skechboy/MAFIA#295]
nekoj clen vo familija ako nakaci mok ne primer mokta na familijata e 16miliona i nekoj igrac ke nakaci 8m i ne go broi to vo mokta na familijata zosto e taka??

**Comment by npoptomov** [comment]
не се пресметува така моќта, вака се пресметува :
играчите што имаат над 500.000 моќ и се пресметува 500.000
играчите што имаат под 500.000 моќ и се пресметува таа моќ што ја имаат

**Comment by skechboy** [comment]
точно такака какко што кажа @npoptomov ова е направено така поради разните новитети што ќе бидат пуштени деновиве во фамилиите.
