### ISSUE TITLE
Луѓе ..... Помагајте итно е !!!!

### ISSUE THREAD

**Issue by Ivorgege** [skechboy/MAFIA#296]
Што срање е ова сеа 

ГРЕШКА!!!
Во обидот да се самоубиеш пиштолот блокира.
Не ти било пишано да умреш денес

Кој знае нека каже ... неможам да напаѓам !!

**Comment by killer3333** [comment]
i jassssss nemozam pomagajte

**Comment by DroWRaNgeR** [comment]
cc treba da si Џепчија  pa da mozes da napagas kolki sto sakas
