### ISSUE TITLE
Предлог : Додавање кука!

### ISSUE THREAD

**Issue by olegz1** [skechboy/MAFIA#298]
Здраво,
Го пишувам овој предлог со цел да и помогнам на играта, да биде поинтересна! :D
Значи вака, би било добро да може да се купи кука ( куките да се скапи, прилично многу скапи ) и секоја кука да има своја цена на пример што поголема толку по скапа, целта ми е куката да ни дава здравије. На пример има 5 врсти на куки ( 1,2,3,4,5 ) 5тата кука највеке енергија дава после секој напад ( да не нападнат ) или слично, а 1вата кука најмалце здравије :).
Пример: Кука бр 1 - Дава 1 енергија после секој напад што не нападнале
Кука бр 2 - Дава 2 енергија
и така до бр 5 :)
А куките би било добро да се скапи ( многуууу скапи ) за да биде исплатливо да ги купат.
На пример Кука бр 1 да биде 10 милијарди! :D
Поздрав, се надевам дека ке го прочитате ова! :D

**Comment by ChillmaxTM** [comment]
so be 10 milijardi nikoj nema da ti ja kupi so tie pari najubavo ke si ja kacam drogata i mokta

**Comment by olegz1** [comment]
Да, не ке може секој да ја купи од што е скапа..
ПА тоа е фората, за тие пари вредна е.
ДА не сакаш случајно за 100 000 да ти ја дадат? :)

**Comment by ChillmaxTM** [comment]
ako gi ima tie kuki ke nemozes ni eden mafijas da ubies

**Comment by olegz1** [comment]
Ке можеш :) 
Би било добро да имаат рок на траење :D
