### ISSUE TITLE
Запомни делот на почетна не работи..

### ISSUE THREAD

**Issue by Pipelin** [skechboy/MAFIA#3]
Мислам дека не работи Запомни делот на почетна каде што треба да се запомни корисничкото име и лозинка. Кога го штиклирам делот Запомни не ми се појавува дали да се зачува лозинката, и мора нонстоп да ја пишувам. 

Исто така доколку ги пополнам полињата и ако притиснам ентер не ме најавува туку треба со маусот да идам до копчето Најави се, добро би било доколку може со притискање на Ентер да се најавува играчот.

**Comment by skechboy** [comment]
Проблемот со ЕНТЕР е решен, но како што ве известив нема проблем со опцијата за запомнување на корисникот т.е. доколку се селектира таа опција доколку играчот го затвори прелистувачот и го отвори повторно тој ќе биде автоматски логиран.
Запомнувањето на лозинката и корисничкото име е забрането заради тоа што некои прелистувачи ги менуваат боите на текст кутијките кога некои податоци се запомнети, па затоа се решивме да го забраниме.
