### ISSUE TITLE
Има Грешка во Black Jack

### ISSUE THREAD

**Issue by redline** [skechboy/MAFIA#30]
Ги ставаш парите ти се погодува BJ или Black Jack ти вели парите се дуплирани а тие не се дуплираат ти остануваат истите пари ... ако може да се поправи овој баг зошто така изгубив многу пари

**Comment by DarkoGit** [comment]
Лелелее колку ме нервира овој баг и ја изгубив едно чудо пари дај стварно поправете го, и исто така уште два други багови кај оваа  игра
1. Картата Кец некогаш се број 1 некогаш 11 да тоа е во ред, но не знам дали ги знаете дека во компјутерските игри кец кога ќе имам со поп(на пример нешто што прави 10) и + 9 не се број 11 туку 1. На овој начин многу пати ми ги зеде парите :(((
2. И Black Jack до сега што сум играл и со другари и во казино и на компјутер сегде правилото вели дека број до 17 а тука брои до 16.

Ве молам поправете ги овие багови........
