### ISSUE TITLE
Предлог : Додавање на претседатели, примиери

### ISSUE THREAD

**Issue by olegz1** [skechboy/MAFIA#300]
Здраво,
Интересно би било доколку има Претседатели и примиери на мафиа.мк :).
Секој мандат на еден Претседател да би траел 20 дена, а на Премиер 10 дена :)
Целта во тоа е што кога си претседател можеш да напагаш а да не те напагаат :) 
А примиер неможеш ни да напагаш ни да те напагаат! :)
Интересен предлог се надевам дека ке го видите! :)
Поздрав

**Comment by andzelo** [comment]
mafiata ne e drzava pa da ima pretsedateli i premieri :D

**Comment by gimen1001** [comment]
haha premier ni da napagas ni da te napagat lol pa togaj koj ke saka da bide premier
