### ISSUE TITLE
Неколку предлози

### ISSUE THREAD

**Issue by npoptomov** [skechboy/MAFIA#301]
Мислам дека овие предлози кои ќе ги кажам се интересни...
1.Во врска со аеродромите, железничките, автобуските, мислам дека на никој не му се исплаќа да ги купува, освен за извршување на мисиите за ништо се нема корист. Мислам дека е подобро вака да се направи : Не само од патувањето од мафијашите да се зимаат пари туку и да се направи население т.е жители и од нив да се зима пари, на пр. ако сте сопственик на некој голем град секојдневно да патуваат неколку илјади луѓе, сакам да кажам да се направи замислени луге кои божем патуваат, и на пр. ако во некој град има многу мафијаши, обичните граѓани да одат во други градови итн. итн.
2.Во врска со заштитата од мафијата, мислам дека не е добро направено, која и да било светска мафија да штити некој, тоа не значи дека тој е недопирлив, така да мислам дека и
да има заштита сепак тие што се 5 пати појаки од него да можат да го напаѓаат.
3.Воведете нешто мотори, автобуси за крадење, и мислам дека би било добро доколку во продавниците ставете да може да се купува автомобили и со нив да се тркаме.
4.Во врска со фамилиите, доколку основачот ја напушти фамилијата , да одреди кој ќе биде негов наследник, т.е да назначи друг основач, а не да пропадне фамилијата исто и доколку биде убиен основачот да ја изгуби функцијата основач и таа да му биде доделена
на негов помошник кој предходно сам ќе го избере.
5.Тоа со нападите веќе го имам споменато во друг пост, доколку играчот на одреден мафијаш му земе повеќе од 50% здравје, тој да биде киднапиран од него, но да постои
мала веројатност од 5-6% тој да избега или пак да му даде пари за овој да го пушти!
Има уште многу интереси идеи, но сега не ми текнува во моментот, поздрав се надевам  дека моите предлози ќе бидат корисни за сите!

**Comment by olegz1** [comment]
Се е ОК, само ова за 5тиот предлог... 
Имаш право, ама мн е пореално да биде како што е сега.
На пример. Ако ја дојдам и фатам некој му скршам заби коски, и после тоа некој со пиштол довага и го убива? :)
Како што викаш ти а полесно да, ама финтата е да биде потешко! :D
Поздрав

**Comment by ChillmaxTM** [comment]
da:1,3,4,5
ne:2

**Comment by npoptomov** [comment]
olegz1 , pa i vaka e realno be, ti ako napagas nekoj , i go tepas non stop, i dojde pred umiranje sigurno nema da dades drug da go ubie t.e. nema da go napagas na sred ulica za drug da moze da go ubie tuku ke go odneses na nekoe tvoe mesto i tam sto sakas ke mu pravis

**Comment by andzelo** [comment]
bravo nikola stvrano me budi idejata da zboreme so skechboy da se sredi igrava mn dobro :))
i od merak da igras vaka ne
