### ISSUE TITLE
Предлог : Повеке сефови!

### ISSUE THREAD

**Issue by olegz1** [skechboy/MAFIA#302]
Здраво,
Незнам зашто можеме толку малце сефови да имаме?
Ако имаме многу пари и идеме на одмор, нема да бидеме спокојни зашто повекето од парите ке ни се во банка на рм. И ако не убијат сите пари ке ни ги земат..
Поздрав

**Comment by Stefanbt8** [comment]
Игра е брат... Јас кога ќе одам на одмор не верувам дека на мафиа.мк многу ќе мислам :D

**Comment by olegz1** [comment]
Абе имаш право но, нејкам да ми ги украдат парите! :)
НИ ја нема да мислам на тоа али нејкам да ми ги земат, а ако ми убијат! :D
