### ISSUE TITLE
bag bag baaaaaaaaaaaaaaagggg !!! :@:@:@

### ISSUE THREAD

**Issue by lion4e** [skechboy/MAFIA#306]
ima BUG na mafia.mk 24h imam zashtita i me ubija -.- popravete go i imav 2 avtobuski Милано и Струмица... a acc mie "lion4e"

**Comment by ChillmaxTM** [comment]
lele i ti zamaaa 900m :D a Ganster rece deka ti kazal deka te napagame :D:D:D:Dna msn i na fb di kazal:D:D:D:D:D

**Comment by Wizardx** [comment]
pa koga nemas vlezeno 2 meseci so sakas 24 sati zastita :D lol
