### ISSUE TITLE
Баг со патување

### ISSUE THREAD

**Issue by Wizardx** [skechboy/MAFIA#308]
Купувам билет за воз во 9:40 и чекам да отпатувам дојде 10:00 и ми пиши ти го чекаш возот во 11:00 часот како можи вака незнам.
Еднаш купив билет за авион за Скопје од Самара за во 10:15 часот и дојде 10:15 и не отпатува гледам ми пиши ти го чекаш авионот за Скопје во 10:45 часот а го купив пред 10:15.

**Comment by ChillmaxTM** [comment]
За воз се чека 51 минута за автобус околу 30 минути со авион се чека 20 минути читајте што пишува.
