### ISSUE TITLE
Патување  - Баг

### ISSUE THREAD

**Issue by SMacedonia** [skechboy/MAFIA#31]
Купив билет за Автобуска Станица за во Софија, автобусот требаше да замине во 00:30 часот, но сега одам повторно на Автобуска Станица и ми пишува дека автобусот за Софија заминува точно во 1 часот.

**Comment by skechboy** [comment]
Е па ништо ќе чекаме до 1 часот за да ја детектираме грешката :)

**Comment by skechboy** [comment]
Ја детектиравме грешката ќе ја одстраниме за брзо врме :)

**Comment by supermen** [comment]
а истото е и со аеродромите, требаше да патувам од Белград во Волгоград, но секогаш летот се поместува пола час подоцна.

**Comment by Pipelin** [comment]
Ќе го поправат сега...

**Comment by skechboy** [comment]
Мислам дека сега се е ок :) Го затварам проблемот :)
