### ISSUE TITLE
Cekanje!!!

### ISSUE THREAD

**Issue by slavemkd** [skechboy/MAFIA#312]
Da napravete koga se napagja na nekogo da se ceka pomalku. Na primer jas cekam po 8 minuti i 30 sekundi da napravete da cekam po 3 minuti i 30 sekundi.

**Comment by barcellona** [comment]
@slavemkd не може да се чека помалку на секој напад дава +15 секунди , колку повеќе напаѓаш толку повеќе треба да чекаш.

**Comment by gimen1001** [comment]
nogu se 15 sec od sekoj napad :S trebalo po 5 sec da napravat
