### ISSUE TITLE
ПРЕДЛОГ - ДОПИШУВАЊЕ

### ISSUE THREAD

**Issue by kikec2000** [skechboy/MAFIA#317]
ДА МОЖЕ ДА СЕ ДОПИШУВАМЕ СО КОРИСНИЦИТЕ ОД МАФИА И ДОДЕКА СМЕ ВО ЗАРВОР !

**Comment by Trajkovski** [comment]


**Comment by npoptomov** [comment]
pa toa e ovozmozeno :D

**Comment by kikec2000** [comment]
pa da ama online da bide !!
