### ISSUE TITLE
Како е можно ова??

### ISSUE THREAD

**Issue by BullDuzeR** [skechboy/MAFIA#325]
Здраво на сите,се уклучувам на мафиа и ми фалат битки за х4 капацитет на дрога,но зафатен сум со други работи наоѓам мафијаш и само го напаѓам на одредено време како што е потребно.Но незнам како е можно во кеш имам 13 милиона и направив 3 битки имам 9?? Админи ве молам помогнете ,а и секако најдов послаб мафијаш од мене не сум ќорав ве молам решете го ова 3 пат ми се дешава и ми летаат 20 милиона безвезе!!!

**Comment by DonMaster** [comment]
aj be pa ti za 20 milioni... xD
