### ISSUE TITLE
Mozebi ke vi se dopadne. :D

### ISSUE THREAD

**Issue by slavemkd** [skechboy/MAFIA#328]
Ви предлагам да направите да може мафијашите да си подзајмуваат пари.

**Comment by npoptomov** [comment]
adminite mnogu pati imaat razmisluvano na ova prasanje..no, na krajot resile da ne ja vovedat ovaa opcija bidejki se zgolemuva moznosta za nekorektno odnesuvanje..t.e prefrlanje pari od multi accaunti taka da propaga ovaa ideja..
