### ISSUE TITLE
Мала грешка кај продавницата 

### ISSUE THREAD

**Issue by Pipelin** [skechboy/MAFIA#33]
Ова се појавува: http://pipelin.ws.mk/files/encode.png незнам дали е до некоја буква и јас имам ваков проблем понекогаш на некои страници...
Да не е до мене незнам...

**Comment by Pipelin** [comment]
��������������������

Да има и на други :(

**Comment by skechboy** [comment]
Запознаети сме со ова ќе го решеме во најбрза идинина.

**Comment by skechboy** [comment]
Проблемот е одстранет. Ти благодарам за извезстувањето.
