### ISSUE TITLE
Предлог "Затвор"

### ISSUE THREAD

**Issue by andzelo** [skechboy/MAFIA#333]
Мислам дека ќе биде подобро ако стануваме помокни и побогати мафијаши побавно ... еве супер идеја...

НА ПРИМЕР ХАКНИ ЈА СТРАНИЦАТА НА МВР АКО СИ ВО СЛАБИТЕ РАНГОВИ ДА ИМАШ ПОМАЛКУ ШАНСА ДА УСПЕЕШ ИЛИ ПРИМЕР 15% А ВО СПРОТИВНО АКО НЕ УСПЕЕШ ДА ОТИДЕШ ВО ЗАТВОР НА СЛЕДЕН ПЕРИОД :

АМА АКО УСПЕЕШ ДА ЈА ХАКНЕШ ДА ЗАРАБОТИШ НА ПРИМЕР 10 МИЛИОНА

АКО СИ
1   Граѓанин
2   Поттрчко ДА ПРЕСТОЈУВАШ ПОВЕЌЕ ОД 20 ЧАСА

3   Џепчија
4   Крадец
5   Макро
6   Гангстер ДА ПРЕСТОЈУВАШ ПОВЕЌЕ ОД 15 ЧАСА

7   Чистач
8   Убиец  ДА ПРЕСТОЈУВАШ ПОВЕЌЕ ОД 10 ЧАСА

9   Лидер   ДА ПРЕСТОЈУВАШ ПОВЕЌЕ ОД 5 ЧАСА

10  Кум ДА ПРЕСТОЈУВАШ ПОВЕЌЕ ОД 2 ЧАСА

И ДА НАПОМЕНАМ КОЛКУ ПОВЕКЕ ПРОБУВАШ ДА ИЗВРШИШ ТОЛКУ КЕ ИМАШ ПОВЕКЕ ШАНСА  ДА УСПЕЕШ...

**Comment by gzlee** [comment]
ako ja napravat taka igrata kako sto vikas ti nema da ima ni 20 luge sto ke ja igrat.........predlogot ti e od glup najglup

**Comment by andzelo** [comment]
epa nema bratce odma da odes da ja haknes stranata ... prvin ke gi raboits poslabite raboti zatoa se staveni ;) ke krades lizalki od deca i velosipedi taka e od pocetok !

**Comment by gzlee** [comment]
pa i sega e taka lizalka mozas da odkrades a odi na toa da ograbis trgovski od 10 pati 2 ke ti uspee taka da dobra e igrata nema sto da se meni osven edno...............Da moze nekoj pojak da ti pozajmuva paricki koli i tn

**Comment by boge** [comment]
glup predlog
