### ISSUE TITLE
KAKO E OVA MOZNO

### ISSUE THREAD

**Issue by mustrak** [skechboy/MAFIA#335]
ADMINI KOGA KE SAKAM DA NAPADNAM NEKOJ STO IMA POMALA MOK OD MENE,MI VIKA DEKA PISTOLOT BLOKIRAL PRI OBIDOT ZA UBISTVO.

PRIMER: JAS IMAM 2 MILIONI MOK i sum od familijata Los Bandits,NAOGAM NEKOJ OD FAMILIJATA King Of Death I TOJ IMA 1 MILION I 900 ILJADI MOK.I SAKAM DA GO NAPADNAM,A I DVAJCATA SME VO ISTI GRAD,I KOGA KE STISNAM NAPADNI MI VIKA DEKA PRI OBIDOT ZA SAMOUBISTVO PISTOLOT BLOKIRA.

AJ RAZMISLETE ZA OVA VE MOLAM!

**Comment by andzelo** [comment]
so rang si ?

**Comment by npoptomov** [comment]
nisto netreba da se razmisluva...toa se slucuva oti izgleda e pogolem rang od tebe
