### ISSUE TITLE
[ПРЕДЛОГ] сеф

### ISSUE THREAD

**Issue by KP3T3H** [skechboy/MAFIA#338]
предлагам да може да се купуват повеќе сефови, дека вака кога ќе идам на одмор парите во банка ризикувам да ми ги земат ако ме убијат

**Comment by npoptomov** [comment]
ima alternativa i za toa, ili gi staj na mok ili daj pw na nekoj da vnimava ili gi doniraj u fam :D

**Comment by gimen1001** [comment]
da treba da se naprave da mozeme da kupuvame poveke sefovi
