### ISSUE TITLE
Предлог: Пораките на мафиа да бидат ограничени по страна

### ISSUE THREAD

**Issue by Pipelin** [skechboy/MAFIA#34]
Предлагам на мафиа кај делот пораки да има ограничено пример 10-20 пораки да се прикажуваат

Слика: http://pipelin.ws.mk/files/mafiaporaki.png морав да одзумирам страницата за да испадне на една слика, иначе во нормала треба многу да се скрола надолу...

Мислам дека ова е добар предлог. 
Ете заборавив долго време немам отворено на бета мафиа, како беше таму? знам дека немаше вака многу пораки, или сум заборавил :)

**Comment by skechboy** [comment]
Ограничени се на точно 25 пораки :) колку и што има на сликата доколку си имал 1+ порака ќе ти се отвореле 2 страници. Како и да е утре ќе го намалиме бројот на 15 пораки на страница.
