### ISSUE TITLE
ГОЛЕМ ПРЕДЛОГ

### ISSUE THREAD

**Issue by bojmaliev** [skechboy/MAFIA#341]
Јас мислам дека  Mafija.mk  треба да направи секој да се логира со Е-Пошта и Лозинка бидејќи кога се логира со Корисничко име многу хакери ако ја дознаат лозинката некако на некој корисник лесно можат да му флезат во Акаунтот  бидејки Корисничкото име е јавно но сепак на Mafija.mk никаде не ја пишува Е-Поштата на некој Мафијш па така на хакерите ке им биде потешко да ја најдат и Е-поштата на некој Мафијаш и мислам ако се воведе ќе почнат пополека да се намалуваат пробивањата на Лозинките и флевањето на други мафијажи во нивните профили..

Со Почит. Bojmaliev

**Comment by Imawsome** [comment]
te podrzuvam

**Comment by aNdzel0t** [comment]
Добар предлог :)

**Comment by skechboy** [comment]
Ако корисникот се логира со Е-Пошта поголема е веројатноста истата да биде откриена преку некој логер на лозинки и слично... Затоа го користиме овој систем, а во случај да лозинката биде откриена некако корисникот секогаш може да си ја промени лозинката преку својата е-пошта.
