### ISSUE TITLE
Предлог за затвор-Обавезно прочитајте

### ISSUE THREAD

**Issue by boy1** [skechboy/MAFIA#344]
Еве еден голем предлог за затвор
-Да може да се бега од затвор...

**Comment by bojmaliev** [comment]
dobra idea ama ako ne uspees da izbegas  tvoeto vreme vo zatvor da se duplira ako na primer si bil vo zatvor 1 minuta posle neuspesnoto probuvajne za da izbegas tvoeto vreme se duplira na 2 minuti

**Comment by boy1** [comment]
da

**Comment by boge** [comment]
collllll predlog
