### ISSUE TITLE
еден предлог од мене :D

### ISSUE THREAD

**Issue by boge** [skechboy/MAFIA#345]
кога ќе играме мафиа.мк и кога сме во затвор да можеме да си го гледаме профилот и други профили само да неможеме да извршуваме злосторства,Уште еден предлог кога ке играме мафиа.мк да има фм радио само кога ке играме да не ни кочи :D се надевам ке биде интересно

**Comment by gimen1001** [comment]
ke si plakas za da izlezes od zatvor :)
