### ISSUE TITLE
Ve molam procitajde

### ISSUE THREAD

**Issue by gimen1001** [skechboy/MAFIA#349]
Da se namale vremeto od napadite da ne se zgolemuva po 15 sec da e po 5 sec

**Comment by npoptomov** [comment]
ne e los predlogot, bidejki isto e dali ke go napadnes odma ili posle 2-3 minuti

**Comment by gimen1001** [comment]
:D ne e isto dali ke napadnes sega ili posle edna minuta :D ama nogu se +15 sec da se zgolemuva
