### ISSUE TITLE
Мала грешка, не редиректира!

### ISSUE THREAD

**Issue by Pipelin** [skechboy/MAFIA#35]
Доколку самиот кликнеш на линкот не те редиректира на почетна туку останува на http://www.mafia.mk/click линк.. 

Зборам за Мојот таен линк:      линкот кој стои во профилот кога ќе кликнеш сам на себе пишува дека не можеш сам да си бидеш платен убиец!  и потоа останува на линкот погоре, а треба да те враќа на почетна.

**Comment by skechboy** [comment]
Проблемот е решен...
