### ISSUE TITLE
ve molam poglednite

### ISSUE THREAD

**Issue by Imawsome** [skechboy/MAFIA#350]
Vidov deka mnogu mafijasi se otkazaa od igrata bidejki e napravena mnogu teska ....ima 540 stranici so mafijasi,a 200 od niv se igraci so 150 mok(koi se vklucile i se otkazale)...Jas ne velam deka se otkazale poraditeskotijata na igrata,no mozat da poevtinat nekolku raboti....ke napisam nekolku dobri razumni ceni na drogite
Marihuana od 50.000/kg da se smeni na 40.000/kg po moznost 35.000(moja zelba) evra
Pecurki od 75.000/kg da se smeni na 60.000/kg  po moznost 55.000/kg
Amfetamini od 100.000/kg  da se smeni na 80.000/kg  
Extasi od  250.000/kg  na 200.000 po moznost 180.000 kg
Heroin od  500.000/kg  na 400.000 itn
Mene mi e vazno cenata na drogata da se namali barem za 20-25%

I da se namali sansata za odenje vo zatvor posle neuspeh vo vrsenje zlostorstvo ili kradenje koli

Blagodaram...

**Comment by Imawsome** [comment]
ова е само предлог не го сваќајте како некаков вид на навреда

**Comment by npoptomov** [comment]
ne 20-25% tuku rabotite treba da poeftinat mnogu poveke, treba da se napravat cenata da bide kako vo realnosta, kako moze mariguana da bide 50 000 evra od kilo ? toa nema sansi, treba da se namalat cenite kako sto se vo realnosta
