### ISSUE TITLE
greska vo napagjanje

### ISSUE THREAD

**Issue by Iniesta** [skechboy/MAFIA#351]
Koga napadnes nekoj i koga kliknes napadni te vrakja na pocetna...

**Comment by Imawsome** [comment]
немаш поени за напад?

**Comment by Iniesta** [comment]
imam poeni ama taka pravi nz i posle 3-4 pati koga ke probam posle mozam da napagjam

**Comment by Imawsome** [comment]
мош е од заштита за ауто кликери

**Comment by npoptomov** [comment]
da toa e novost i e napraveno za zastita od auto atakerite
