### ISSUE TITLE
ПРЕДЛОГ ЗА ПОДОБРУВАЊЕ НА ИГРАТА

### ISSUE THREAD

**Issue by BullDuzeR** [skechboy/MAFIA#352]
Вие направивте промена во играта за да се заштитите од ауто кликерите,мислевте дека направивте подобро,но направивте полошо.Еве го мојот предлог за заштитување од ауто кликерите.Ќе направите секој мафијаш да неможе да стои на туѓ профил повеќе од 2 минути. Значи доколку е пуштен некој со ауто кликер и си го наместил маусот на нападни,ќе неможе да напаѓа бидејќи на секој 2 минути страницата ќе му се враќа на HOME,вие ќе направите сите мафијаши да неможат да се задржaт на некој профил повеќе од 2 мин,после 2 минути страницата автоматски да му оди на HOME.И во најскор рок направете ја оваа промена неможеме да направиме 1 убиство заради вашата промена на играта ова ви го пишувам во име на СИТЕ МАФИЈАШИ

**Comment by Imawsome** [comment]
Те подржувам брат!

**Comment by npoptomov** [comment]
ej ne mi e jasno kakva korist imate ako napagate so f5 ? sega site ja znaat taa finta i site napagaat so f5 i pak nema da mozes da go zemes ubistvoto!
vaka e podobro koj najbrzo ke stisne na napadni toj da si go zeme, sreka e vo prasanje :D

**Comment by gimen1001** [comment]
vaka e dobro ama da napraat da ne kasne :S gore mi pise xx:59:59 a  xx:00:01 e  :S
