### ISSUE TITLE
Злосторствата

### ISSUE THREAD

**Issue by Imawsome** [skechboy/MAFIA#353]
Да се зголеми максималната корист од злосторствата.Јас сѕм поттрчко и имам 40% шанса да украдам лижалка што има корист од 50евра...??Некој ако ми кликне на мојот таен линк ја добивам 600 евра.Треба да се зголеми користта барем на злосторствата што се на првата страна...Можете да направете малку баланс затоа што имам 34% шанса да украдам Toyota Prius од кој ќе заработам 15000 илјади,а зза злосторство имам 44% шанса да заработам максимум само 50.Нема смисла.....

**Comment by gimen1001** [comment]
najglupoto nesto u igrata e so se krade lizalka lol kakov mafijas e taj so ke krade lizalka :D

**Comment by npoptomov** [comment]
ne treba da se zgolemi lizalkata tuku treba da se namali! kako moze da imas 50evra korist od edna lizavka ? ili treba kompletno da se izbrise toa zlostorstvo zasto lizalkata e 5 denari a ne e 50 evra...
inace podobro ke bide tajniot link da se aktivira posle rang makro, bidejki ako si graganin nemozes da naogas plateni ubijci neli ? seuste ne si mafijas
