### ISSUE TITLE
..

### ISSUE THREAD

**Issue by filipgeek** [skechboy/MAFIA#355]
Pred dva dena koga ke ja otvorev mafia.mk mi odbrojuvashe 1 den 20 casa 12min...
sega pomina toa vreme i pak nemozam da se logiram.. 
ve molam proverete go ova username mie: filipgeek!

**Comment by filipgeek** [comment]
i zaboraviv da dodadam ova se slucuva samo od mojot kompjuter..

**Comment by npoptomov** [comment]
do tebe e ne e do igrata, zemi procisti gi registrite i cookies i cashe na prebaruvacot i probaj odnovo

**Comment by filipgeek** [comment]
go napraviv, sega mozam ta se log.. fala
