### ISSUE TITLE
ПРЕДЛОГ

### ISSUE THREAD

**Issue by DeathPenalTy** [skechboy/MAFIA#356]
da mozes kolku sakas da go tepas mafijasot da ne ti pokazuva       e napadnat 5 pati vo posledniot cas najdi si nekoj drug glupo e vaka nikako ne mozes edvaj ke go ubies ako sakate da go trgnete ke bide mnogu pointeresno ve molam!!!?!?!?!?!?!?

**Comment by gimen1001** [comment]
ako bide taka ke se ubivat mafijasi za 3 saata

**Comment by DeathPenalTy** [comment]
ama so vaka ne e interesno ja pocnav eden mafijas da go tepam okolu 00:00 sat i go tepav se do sabalje na sekoj sat po 5 pati go tepav i nekade okolu 6 sabajle na malku bese i togas se uklucia poise igraci i mi go zemaa da ne e ova na seko 1 sat po 5 pati da napagas ke go utepav barem po 10 pati na eden sat dobro ke e!

**Comment by npoptomov** [comment]
abe deathpenaly, ti misles deka ke bides online cel den, pa ti ke se iskluces i za 3 casa ke te ubijat pa posle da te vidam sho ke praes

**Comment by gimen1001** [comment]
ako e taka po povise pati jas u deno po 5 ubistva ke si praam

**Comment by DeathPenalTy** [comment]
npoptomov pa ke kupuvas zastita  i to ke bide jako nonstop ke se ubivame
