### ISSUE TITLE
Predlog

### ISSUE THREAD

**Issue by gorgej** [skechboy/MAFIA#358]
Koga krades kola ili zlostorva koga pravis da ne se  ceka po 5min ili poveke... tuku po 1min mislam deka e dobar predlog za site ako e mozno po 0:30

**Comment by npoptomov** [comment]
hahaha i za 1 den ke stignes rang kum 100%, rabotata e da e poteska igrata

**Comment by gimen1001** [comment]
1min :) po 15min da se ceka od MVR
