### ISSUE TITLE
Oдбројувањето се појавува повторно

### ISSUE THREAD

**Issue by Pipelin** [skechboy/MAFIA#36]
Ми се појави одбројувањето во болницата додека бев, потоа еден играч ми прати порака додека пребарувал некој играч му се појавило и него...

**Comment by skechboy** [comment]
Работев на оптимизирање на серверот па ја сопрев играта за кратко :) Сега се е ок. BTW ако му се појавува на некој друг кажи им да ги use the magic keys "CTRL+F5" :) :) :) :)

**Comment by Pipelin** [comment]
тоа и им го пишав :) ок може во Closed
