### ISSUE TITLE
BETA.MAFIA.MK

### ISSUE THREAD

**Issue by kikec2000** [skechboy/MAFIA#360]
IMA GRESKA VO BETA.MAFIA.MK  3 DENA PO RED SE PUSTAM I NEMAM DROGA :D A GI IMAV PRVITE 3 DROGI KUPENO DO DASKA MOZE POMOS??

**Comment by npoptomov** [comment]
ne e toa samo kaj tebe...pred nekoj den pravea promeni vo igrata i sega zaboravile da naprvat igrata da se restartira i sega site stojat u mesto , ama koga ke se vrati skech koj momentalno e vo bugarija ke ja restartira igrata za site denovi i se ke si bide ok
