### ISSUE TITLE
ne moze da se depozira vo fam

### ISSUE THREAD

**Issue by Topkaa** [skechboy/MAFIA#361]
cekam vo 1:00 casot da gi depoziram parite zatoa sto mislev deka nekoj kod napminal dnevnite transakcii ama pak pisuva 0 i ne moze da se depozira de videte i prasav drugi osnovaci i tie go ime istiot problem ako moze kaj Los Bandits da depoziraat

**Comment by npoptomov** [comment]
pa i depoziranjeto ne e potrebno bidejki nema napadi vrz familii vo ovaa sezona, inace toa e greska sto transakciite za depoziranje ne se restartiraat sekoj den, se nadevam deka ke go popravat
