### ISSUE TITLE
Predlog za podobruvanje na igrata.

### ISSUE THREAD

**Issue by FreaKMan007** [skechboy/MAFIA#364]
koga patuvame primer vo belgrad dokolku ostaneme 1 den vo taa drzava da pocne da ni se odbrojuva kirija bidejki prestojuvame vo hotel ili pak vo nekoja kuka,a kirijata da bide 10-15 m na den a,dokolku ne sakame da sme vo hotel ili kuka,da mozeme da kupime stan ili kuka :) a,cena na kuka ili stan da bide 200.000.000M

**Comment by npoptomov** [comment]
ti normalen li si ? si videl li kuka da bide 200m ??? kukjite se po 100.000evra

**Comment by BullDuzeR** [comment]
pa ti izgleda glup si sekoj ke moze da si kupi za 100.000 evra be supak

**Comment by Nikolaa** [comment]
a Istooo takaaa mozii da imaaaa i iii Sekojjj Mafijashh Da Si Vrabotuvaaa Svoii Lugjee....da rabotat za negoo...i da gi plakaa......kamionii da imaa za sverc na Drogaa i takvii rabotii...:)))

**Comment by Roodman** [comment]
ми се допаѓа идејата на Nikolaa

**Comment by v1kt0r** [comment]
Na igrava bidejki ne se soglasuvam so 100 iljadi evra tocno e tolku deka vredat no samo vo realniot zivot ova e igra i mislam deka 1 milion treba da bide
