### ISSUE TITLE
ПРЕДЛОГ

### ISSUE THREAD

**Issue by DeathPenalTy** [skechboy/MAFIA#368]
ДА мозе да се менува името на пример за   50 милиони или 100  да го смениш името

**Comment by kikok** [comment]
i jas mislam taka da se napravi ako ne pa 500m pari da se dava na satarata ama da biva da go smenish nickot sea jas igram an drgar mi profilot toj mi go dade a da ne biva da se smeni (toa e kako da go promoviram nickot) pozz..
