### ISSUE TITLE
Greshka - Alkohol

### ISSUE THREAD

**Issue by pigmy** [skechboy/MAFIA#37]
Imam 50kg liker koi nemozham da gi prodadam..
Mi vika policijata ti e zad petite nemozhesh da  go prodadesh alkoholot vo ovaa drzhava..
Dali e toa namerno ili ne?
Zashto zboruvav so eden drugar i toj mozhe normalno da prodava alkohol.
Fala, pozdrav

**Comment by Pipelin** [comment]
Треба да смениш држава. Иди во некоја друга држава и таму продај го..

**Comment by pigmy** [comment]
fala i tuka :))
