### ISSUE TITLE
Пребарувач на никови...

### ISSUE THREAD

**Issue by Sbanation** [skechboy/MAFIA#371]
Да има еден пребарувач за никовите да можеме да ги најдеме многу лесно и едноставно...

**Comment by KP3T3H** [comment]
http://www.mafia.mk/search

**Comment by Sbanation** [comment]
Не бе пријателе јас мислев да има на почетна на пр. да не мораме да одиме на пребарувај...OK уживај

**Comment by aNdzel0t** [comment]
што бе толку ти е тешко да идеш пребарувај тука нема ништо сложено..
