### ISSUE TITLE
Predlog

### ISSUE THREAD

**Issue by gimen1001** [skechboy/MAFIA#372]
Zastita od mafiata da mozat da kupuvat site ama 1H zastita da bide 1milion

**Comment by aNdzel0t** [comment]
1) и сега сите можат да користат
2) тоа нема да биде фер за корисниците со послаб ранг

**Comment by gimen1001** [comment]
site mozat i pise ama :D zs da ne bide fer pa ovaka site stavat zastita aj napraj kill

**Comment by gimen1001** [comment]
za sekoj rank da e razlicna cenata

**Comment by gimen1001** [comment]
za kum 1milion

**Comment by aNdzel0t** [comment]
заштитата си е ок според мене а тоа дека за секој ранк треба да има различна цена се согласувам добра идеја е

**Comment by KP3T3H** [comment]
а да се отвори кредит шоп, и таму да има да се купи заштита по желба од 1 час до 1 недела, пример, ако идам на одмор итн.
