### ISSUE TITLE
Greshka - Zatvor

### ISSUE THREAD

**Issue by pigmy** [skechboy/MAFIA#38]
Nemozham da si platam kaucija, ni za mene ni za nekoj drug :))
Fala, pozdrav

**Comment by SMacedonia** [comment]
Ако си осуден на повеќе од 2 минути можеш да платиш, за помалку ќе те ослободат за добро однесување. :)

**Comment by Pipelin** [comment]
Ако времетраењето е помало од 2 мин неможеш да платиш кауција...

**Comment by pigmy** [comment]
Aaa epa ne sum znael :P:))
fala drugar

**Comment by Pipelin** [comment]
Нема проблем ;)
