### ISSUE TITLE
За пораките

### ISSUE THREAD

**Issue by Nexus123** [skechboy/MAFIA#39]
Кога пријавувам порака пораката останува неможе да се избриши.

**Comment by Pipelin** [comment]
Да сега забележав дека пријавената порака не се брише. Мислам дека ова е океј, затоа што ако ја избришеш ти мислам дека админите нема да ја прочитаат.

**Comment by Nexus123** [comment]
Значи кога ќе ја прочитаат ќе се избриши или не? :S

**Comment by skechboy** [comment]
Да да штом ние ќе ја прочитаме и видеме дали треба да се превземе некоја казна ќе  пораката ќе биде избришана.

**Comment by Nexus123** [comment]
Ја прочита ли? вулгарна е пораката а и малку смешна :D:D
