### ISSUE TITLE
Маглата на позадина не е центрирана хоризонтално.

### ISSUE THREAD

**Issue by macstr1k3r** [skechboy/MAFIA#4]
Слика ќе следи некако...

**Comment by macstr1k3r** [comment]
http://ubuntuone.com/p/TJr/ Скриншот

**Comment by Pipelin** [comment]
Јас ја немам маглата :) кај мене страната е на фул

**Comment by skechboy** [comment]
Ти благодарам за известувањето. Грешката е исправена
