### ISSUE TITLE
Сателит - Баг

### ISSUE THREAD

**Issue by SMacedonia** [skechboy/MAFIA#40]
Си купив сателит, но кога отидам во Будни мафијаши пишува дека градот им е скриен иако имам сателит, ве молам побрзо средете.

**Comment by Pipelin** [comment]
Да сега баш и јас тоа го забележав, исто така  пишува: 
Нема ограничувања, во моментот ти имаш: 1 што значи дека може повеќе од еден.

Мислам дека вселенската станица ја врши таа работа, баш ќе ја купам да видам.

**Comment by skechboy** [comment]
За со сателит можеш да ја гледаш локацијата на само еден мафијаш т.е. мора да го отвориш неговиот профил за да ти ја прикаже локацијата негова. Додека за да ја гледаш локацијата на повеќето мафијаши во листите мора да имаш сателитска станица.

**Comment by SMacedonia** [comment]
Ахх барем да знаев за џабе си ги дадов парите, сега кој ќе збира 500.000 ... во секој случај фала на одговорот. :)
