### ISSUE TITLE
NEMOZAM DA KRADAM AVTOMOBILI

### ISSUE THREAD

**Issue by DeLuxKeyboard** [skechboy/MAFIA#403]
http://pic.mk/images/6cH5P.jpg

TOA MI IZLEVA KOGA SAKAM DA KRADAM KOLI 
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by skechboy** [comment]
Освежи ја страницата http://www.mafia.mk/stealcars со Ctrl+F5

**Comment by DeLuxKeyboard** [comment]
fala brat :)
