### ISSUE TITLE
МАФИА.МК

### ISSUE THREAD

**Issue by DeadBoss** [skechboy/MAFIA#41]
Би било многу добро ако одобрите да се објавува нешто на МАФИА.МК на Фејсбук
Би се презентирале многу линкови и би разменувале многу работи !
дали ке одобрите 
пишете !

**Comment by skechboy** [comment]
Одобрено :) :)

**Comment by DeadBoss** [comment]
Фала многу скеч !

**Comment by Nexus123** [comment]
Значи сега можат ли сите да ви кликнуваат на ТЛ ?

**Comment by DeadBoss** [comment]
Ова е за да можат да се постират објави на МАФИА.МК на фејсбук !

**Comment by ChillmaxTM** [comment]
Одобрено
