### ISSUE TITLE
POMOSS!!

### ISSUE THREAD

**Issue by mafijas** [skechboy/MAFIA#412]
Dali mozi da mi kazi nekoj kako da napram stanici vo aukcii sto e?? kako da napram aerodromi, zeleznicki и avtobuski stanici??

**Comment by bojan135** [comment]
што збориш бе ти ??????? lool hahahahahahahahahahaahah како да направиш станици бее хахахахахахаахахах

**Comment by mafijas** [comment]
PA STANICIIIIIIIII!!!!!!!!!!!! za da odis vo skopje,ohrid,bitola,kumanovo...
