### ISSUE TITLE
Укочување на процентот на рангот

### ISSUE THREAD

**Issue by Pipelin** [skechboy/MAFIA#42]
Можно е да се закочи процентот на рангот кај некој играч, еден баш ми се пожали дека цел ден извршувал некои активности и рангот му останал ист. И од сабајле до сега го гледам останат е на Поттрчко - 52.75 %  значи не е помрднат...

**Comment by skechboy** [comment]
Не е можно да му закочи процентот. Но можно е да има лоша среќа :) :) како и да е го оставам проблемот ортворен за да се преиспита проблемот...
