### ISSUE TITLE
zlostorstva 

### ISSUE THREAD

**Issue by misterdarko** [skechboy/MAFIA#426]
abe koj znae zosto ne mi gi otvara zlostorstvata samo ja dava pozadinata na mafia mk i dava godina mesec den i cas i se e nula koj znae neka mi odgovori zosto e ova vaka :((((((((((((((((((((((((((99

**Comment by skechboy** [comment]
Освежи ја страницата со Ctrl+F5 и би требало да ти се реши проблемот поззз

**Comment by misterdarko** [comment]
http://www.mafia.mk/crimes ne be drugar nesaka da cue

**Comment by misterdarko** [comment]
aaa dobro e sege dobro fala ej :DDDDDDDDDDDDDDDd
