### ISSUE TITLE
Тркало на СРЕЈЧАТА >)

### ISSUE THREAD

**Issue by SephirothMAFIAMK** [skechboy/MAFIA#43]
Вчера го свртев тркалото на среќата околу 11 саат. Денес ми вика дека денес веќе сум го свртел, а не е точно!

**Comment by DeadBoss** [comment]
и кај мене така е :s

**Comment by Pipelin** [comment]
Мафиа вчера беше пуштена во 3 часот на пладне, тркалото ти си го свртел во 11 часот на вечер, ќе треба да чекаш до 11 часот на вечер според моја претпоставка..

**Comment by klikstermkd** [comment]
Тркалото на среќата може да се користи само еднаш во денот, т.е. на секои 24 часа.

**Comment by skechboy** [comment]
Да тркалото можете да го вртете еднаш на секои 24 часа :)

**Comment by JasSumToj** [comment]
a ne sekoj nareden den..
ti ke go svrtis vo 23:59 posle vo 24:00 pak sakas da go vrtis..

**Comment by KP3T3H** [comment]
подобро би било да се ресетира тркалото во 00:00 часот, така секогаш ќе знам кога повторно ќе можам да го вртам а и сепак останува да се врти еднаш дневно.
