### ISSUE TITLE
BUG-travel-avtobus

### ISSUE THREAD

**Issue by kuche** [skechboy/MAFIA#45]
Го чекаш автобусот за Нови Сад ...
Тој заминува точно во 14:30 часот

Откажи го патувањето.... se ushte ne sum praten ... a saatov e 14:33

**Comment by klikstermkd** [comment]
Има некој проблем со патувањето. Никој не можи да патува. Ова важи и со воз и со авион.

**Comment by skechboy** [comment]
Мислам дека проблемот е одстранет сега. За секој случај го оставам проблемот отворен.
