### ISSUE TITLE
imam pari vo banka a bankarska smetka nemam 

### ISSUE THREAD

**Issue by killer159** [skechboy/MAFIA#46]
nemozam parite od banka da si gi izvadam :(

**Comment by DeadBoss** [comment]
Банкарската сметка е за да можиш легално да вадиш пари 
и не го мачете Скеч овде бе
Ти пиши брат Грешки / Предлози а ова твоето е ПРАШАЊЕ а не Грешка или Предлог !

**Comment by klikstermkd** [comment]
За да можеш да ги извадиш парите од банка ти треба банкарска сметка, а за да можеш неа да ја купиш треба да имаш во ќеш 50.000 евра. Кога ќе ја собериш оваа сума купи си сметка и ќе можеш да си вадиш пари. :)

**Comment by lion4e** [comment]
a taka... :))
