### ISSUE TITLE
Alkohol...

### ISSUE THREAD

**Issue by lion4e** [skechboy/MAFIA#47]
Probvam da prodavam vidi sho veli :

ГРЕШКА!!!
Полицијата ти е позади петите!!!
Не можеш да го продадеш алкохолот во оваа држава.
OK

**Comment by skechboy** [comment]
Алкохолот мора да го продадеш во друга држава

**Comment by LjubeGVG** [comment]
otidov pak ne raboti

**Comment by skechboy** [comment]
Доколку кога си отидил во друга држава и таму си купил алкохол нема да можеш да  да го продадеш алкохолот во таа држава.
