### ISSUE TITLE
nekolku bagovi vo igrata :)

### ISSUE THREAD

**Issue by WoOoZy** [skechboy/MAFIA#48]
nemozes da ja platis kaucijata neznam vo sto e problemot klipovitet od youtube nemozes da gi objavis,nemozes da dodades prijatel.. i edno prasanje koga ke bide forumot ? fala odnapred

**Comment by klikstermkd** [comment]
Кауција можеш да платиш доколку си повеќе од 1 минута во затвор. Видео од Youtube се става на овој начин:

Пр. За ова видео http://www.youtube.com/watch?v=W1SHkkBDZK0

[youtube]W1SHkkBDZK0[/youtube]

Значи го ставаш само ID-то на видеото и тоа е тоа. :)

Додавањето на пријатели моментално не работи но за брзо ќе биде во функција.
