### ISSUE TITLE
ГРЕШКА!!!ПОПРАВКА НА АВТМОБИЛИ(КОЛИ)

### ISSUE THREAD

**Issue by hvardovski** [skechboy/MAFIA#49]
Украдов кола Mitsubishi Lancer EVO9 10% оштетена,отидов во гаража со 32.000 и кликам поправи и ми вели грешка немаш доволно пари.Ве молам поправете го тоа ПОЗДРАВ!!!

**Comment by klikstermkd** [comment]
Провери дали парите ти се во ќеш, затоа што колите единствено може да се поправаат само со пари во ќеш.

**Comment by hvardovski** [comment]
Во ќеш се http://tinyurl.com/24n32wp

**Comment by riba** [comment]
Не треба да ти бидат во кеш треба ти бидат во Народна банка на Р.М
