### ISSUE TITLE
Предлог ( Автомобили )

### ISSUE THREAD

**Issue by DeadBoss** [skechboy/MAFIA#50]
Ако е добар предлогов сакам да направите вака (ако е добар)
-Во гаражата да има и копче како кај пораките -Селектирај ги сите- е во гаражата да има поправи ги сите . А може и да биде според секој вид да се поправаат автомобилите !
Пишете админи ! :)

**Comment by hvardovski** [comment]
Добар предлог

**Comment by skechboy** [comment]
Добар е предлогот ќе го имаме во предвид :)

**Comment by DeadBoss** [comment]
ОК Скеч фала на поддршката ! :)
