### ISSUE TITLE
Bolnica i zatvor 

### ISSUE THREAD

**Issue by rocky-mk** [skechboy/MAFIA#51]
e da napravite ako moze i zatvorot i bolnicata da se kupuvaat.. parite so ce gi davame za lekuvanje ili za kaukacijata na zatvorot da odat kaj sopstvenikot ...

**Comment by hvardovski** [comment]
Не е интересно така тие со ке ги имаат ке бидат најбогати

**Comment by SteFaaN** [comment]
Не би било ок... Сите се лечиме барем 1наш у денот... На шо ќе личи сопственикот =)

**Comment by skechboy** [comment]
Така ќе се даде премногу моќ на сопствениците

**Comment by rocky-mk** [comment]
da se napravi na sekoi dve nedeli da se menuvaat da se davat novi sumi da se kupat .... ili pa kako so se toa kafeterii stavete hoteli benziski pumpi i drugo..
