### ISSUE TITLE
kako se pravat poenite ? :S :S 

### ISSUE THREAD

**Issue by marija123456** [skechboy/MAFIA#55]
kako se dobivaat poenite ? :S :S BRzo admini odgovorite :S:S :(

**Comment by skechboy** [comment]
поените не се прават тие се добиваат :) Тие се збир од многу работи во играта како моќ, пари, почит и уште многу други работи . Би ве замолил во иднина да не поставувате тука вавки прашања затоа што ова е наменето за пријавување на грешки  давање на предлози.

Ти благодарам поздрав.
