### ISSUE TITLE
Предлог за патување

### ISSUE THREAD

**Issue by SteFaaN** [skechboy/MAFIA#56]
Патувањето со воз да биде поспоро од со автобус... И да трае барем некое време ... Вака доаѓа и одма си стигнал многу е нереално ... И не глеам причина возот да биде поскап од автобусот кога на исто време ѓи има а и за исто време патуваат... Фала =)

**Comment by npoptomov** [comment]
ccc ti se si ispomesal ... pa vozot oti na sekoj cas a avtobusot na 30min i avobusot e poskap !!!

**Comment by JackDaniel** [comment]
ако подалеку патуваш мора да одиш со авион ...

**Comment by hvardovski** [comment]
Ne podaleku,vo druga drzava JackDaniel se patuva so avion

**Comment by SteFaaN** [comment]
Nemora vo druga drzhava ako imash vo ista drzhava vo 2 grada aerodrom mozhesh da patuvash recimo od skopje do ohrid a imam igrano mnogu mafia igri pa od iskustvo znam deka e podobro koga se cheka da stignesh =] I da nemozhesh nishto da praish dur patuvash bar 5 10 min vaka celo vreme site patuvaat
