### ISSUE TITLE
Аукции

### ISSUE THREAD

**Issue by SteFaaN** [skechboy/MAFIA#57]
Мислам дека се многу рано... Јас уште немав напраено акаунт а пола беа купени... Можеше тоа после месец дена да се пуштат :S

**Comment by skechboy** [comment]
Секогаш ќе имате можност за нови аукции кога ќе убиете некој сопственик. Би ве замолил да не пишете овде за такви работи затоа што овој дел е наменет за грешки поздрав.

**Comment by SteFaaN** [comment]
Vo red jas te razbiram deka ova e del za greshki ... Ama ne postoi drugo mesto za kontakt so tebe ... Na beta maFijata mi trebashe mnogu ti pishav preku 15 poraki ama ne mi vrati... Pa zatoa se snaogjam ;)

**Comment by DoubleL** [comment]
Bravo stefan ! :)
