### ISSUE TITLE
Баг со трлкалото 

### ISSUE THREAD

**Issue by Pipelin** [skechboy/MAFIA#61]
Иако поминаа 24 часа откако го свртв тркалото, еве и други пријавија дека неможат да го свртат. Некои дури и не го свртиле (како што велат тие) а им пишува свртено, како и да е мислам дека тркалото не се врти и по поминати 24 часа.

**Comment by skechboy** [comment]
Хмммм го тестирав лично јас се си е ок кај мене колку луѓе го пријавија овој проблем ???

**Comment by Pipelin** [comment]
http://pipelin.ws.mk/files/maf1.png
http://pipelin.ws.mk/files/maf2.png

Гледам и DarklorD спомна дека и тој неможел да го сврти.

**Comment by Pipelin** [comment]
Предлагам најдобро е после 01 часот заедно со дрогата да може да се врти за сите. Според мене мислам дека така е најдобро..1 време да има на пример после 00:00 или 01:00

**Comment by skechboy** [comment]
Пипе тркалото на среќета не беше пуштено во 17 часот :) :)

**Comment by Pipelin** [comment]
Да сега можам да вртам. Добив 50% а сум 100% :) нема некоја логика.. Како и да е со времето работи ок.

**Comment by DeadBoss** [comment]
За ова со силата да има во болницата екстра сила копче и до него колку имаме екстра сила и дали сакаме да ја земиме или да стој (од тркалото на среќата !
