### ISSUE TITLE
Грешка: Не прикажување на мафијашот во кој град се наога.

### ISSUE THREAD

**Issue by matru** [skechboy/MAFIA#62]
Иако имам купено Сателит, додека јас сум во поделбите по богатство и моќност на мафијашите мене не ми покажува каде се наога мафијашот односно пишува дека е скриен. Ова не се случува кога влегувам да го видам профилот на играчот. Поубаво е објаснето со сликава: http://pic.mk/images/21292533232.jpg

**Comment by skechboy** [comment]
Не станува збор за грешка. Доколку го прочитате повнимателно описот за сателитот ќе видете дека со сателитот можете да ја гледате позицијата само на еден мафијаш, а доколку сакате да ја гледате локацијата на сите мафијаши мора да имате вселенска станица.

**Comment by Pipelin** [comment]
Епа за да ги гледаш без да ги отвараш ти треба вселенска станица :) вака ќе се помачиш затоа што имаш сателит кој можеш да гледаш само еден мафијаш :)

**Comment by Pipelin** [comment]
Истовремено :)

**Comment by matru** [comment]
Извинете, не го прочитав објаснувањето на сателитот :)

**Comment by Lart** [comment]
Зато читај друг пат

**Comment by ChillmaxTM** [comment]
ako znae :)
