### ISSUE TITLE
nadograduvanje na alkohol.

### ISSUE THREAD

**Issue by alekss** [skechboy/MAFIA#67]
Vcera kupiv 15 gajbi i od koga gi sitnav, ne mi se zacuvaa tie 15 tuku pak mi se vrati na 0, ako nema nekoja greska stv e glupo zosto ke nemozes nikad da imash profit od ova. pozz

**Comment by skechboy** [comment]
Проверив кај алкохолот се си работи како што треба. Ти имаш направено некоја грешка

**Comment by alekss** [comment]
Ok mozebi iam nekoja greska. fala pozz
