### ISSUE TITLE
''Запомни ме'' опцијата не работи 

### ISSUE THREAD

**Issue by npoptomov** [skechboy/MAFIA#68]
опцијата запомни ме не работи а исто така и мозилата несака да ја зачува лозинката... ја зачувува само при регистрација а при логирање несака... што е проблемот ???

**Comment by JackDaniel** [comment]
И кај мене така прави

**Comment by hvardovski** [comment]
I kaj mene isto

**Comment by Pipelin** [comment]
Тоа е така. Целта на  Запомни ме е да не ја зачувува лозинката, туку да те запомни најавен на тој компјутер одредено време, да не те одјавува се додека ти не кликнеш Одјави. А за запомнување на лозинката неможе поради безбедносни причини.

**Comment by npoptomov** [comment]
ne razbiram kakvi bezbednosni pricini... u site online igri i sajtovi u sveto ima za zapomnuvanje... sea ja za sekoj login treba da pisuva racno :@:@

**Comment by Pipelin** [comment]
Да. И кај други игри нема за запомнување :) Барем кај тие понапредните...

**Comment by Cool4life** [comment]
Абе шо ако не работе, па и кај мене не работе

**Comment by JasSumToj** [comment]
i sto tesko ti e da napises User i pw?
pa nemora da igras ako ti e tesko
