### ISSUE TITLE
Predlog 

### ISSUE THREAD

**Issue by kuche** [skechboy/MAFIA#69]
ubavo kje bide ako stavite... na sekoe ubistvo da dodava 10+ respect :) i 25 TL;) i 15 poeni:D

**Comment by DeadBoss** [comment]
Е да да добра предлог ама не по толку помалку ама да има да одбериш на пример
- Ти го уби xxx 
  Сега одбери едно од трите
  10 респект 25 ТЛ и 15 поени
  добро е :)

**Comment by kuche** [comment]
i toa e dobro :)
