### ISSUE TITLE
Проблем со сенката во Злосторства

### ISSUE THREAD

**Issue by Pipelin** [skechboy/MAFIA#7]
Сенката која се појавува во поголемите злосторства малце забегува од нејзината позиција 

Eве слика: http://pipelin.ws.mk/files/mafia2.png каде што сивиот дел е отиден малце надесно и е подолу од местото кое што треба да биде...

**Comment by skechboy** [comment]
Како што можам да приметам овој проблем се појавува само на Firefox нели ?

**Comment by klikstermkd** [comment]
Кај мене сивиот дел го нема, ама е за малце надолу поместен и на Firefox и на Chrome.

**Comment by skechboy** [comment]
@klikstermkd  ако може да додадиш еден принтскрин би ти бил благодарен

**Comment by klikstermkd** [comment]
еве http://pic.mk/images/1231292181391.jpg
