### ISSUE TITLE
ГРЕШКА ВО ТРКАЛО НА СРЕЌАТА

### ISSUE THREAD

**Issue by kikec2000** [skechboy/MAFIA#70]
ВЧЕРА СТИСНАВ  НА ТРКАЛО НА СРЕЌАТА А ДЕНЕС НЕ И ДЕНЕС КОГА СТИСНАВ МИ ВИКА ДЕКА НЕ МОЖЕ ДЕНЕС УТРЕ ПАК!!!

**Comment by becutan** [comment]
точно и мене исто ми викаше

**Comment by skechboy** [comment]
Треба да поминат 24 часа од кога последен пат си играл за да можеш повторно да играш.

**Comment by kikec2000** [comment]
da ama ne moze !
