### ISSUE TITLE
Chat

### ISSUE THREAD

**Issue by LjubeGVG** [skechboy/MAFIA#71]
ke bide ubavo ako mozis da si pisuvas na chat so tvoite prijateli i da moze da imas pove od 25 prijateli

**Comment by kikec2000** [comment]
SE SOGLASUVAM!

**Comment by JackDaniel** [comment]
јас неможам ниту еден пријател да ставам не се покажуваат имињата во Пријатели

**Comment by hvardovski** [comment]
Ako mozi barem so tie 25 da ima chat

**Comment by npoptomov** [comment]
hahah fb edvaj stavi chat a vie sakate mafia.mk da stavi ccccccc

**Comment by babusho** [comment]
i jas se soglasuvam chat e dobro nesto.... i jas sakav da dadam predlog no tuka vidov deka ima otvoreno i pisav :)

**Comment by Cool4life** [comment]
Може чет, и смајловци да можат да се стават у пораки, статуси, матуси такви работи

**Comment by JasSumToj** [comment]
Abe bidete blagodarni i na ova zatoa sto e super vaka
a vo idnina moze da se stavi chat i sl..

**Comment by savesk1** [comment]
moze i muzika u pozadina da se stae nekoja mafijaska, da go ni go digne adrenalinot :D

**Comment by BAD-BOY** [comment]
i jas se soglasuvam ako moze da ima chat super ke bide

**Comment by Roodman** [comment]
мојот предлог е чатот да бидне како кога оставаш коментар на некој профил со смајлиња
