### ISSUE TITLE
Проблем со gravatar.com

### ISSUE THREAD

**Issue by JackDaniel** [skechboy/MAFIA#72]
Во gravatar.com  успешно поставив слика на ист меил што се регистрирав на мафиа.мк ,
но сеуште не ми се појавува во игра а чекам скоро 2 дена . . . 
Значи се прикажува сликата во gravatar.com дека е поставена а во играта ја нема ???
Ако има некое решение пишете

**Comment by skechboy** [comment]
Највероватно не си ја линкувал сликата со твојот е-маил. Обично откако ќе ја поврзеш сликата се појавува за 5-6 минути во играта.

**Comment by JackDaniel** [comment]
да да средив skechboy сум погрешил во ratings требало G rated :)
