### ISSUE TITLE
Дрога - Алкохол каде да продавам 

### ISSUE THREAD

**Issue by JackDaniel** [skechboy/MAFIA#73]
Грешка !!!
Полицијата ти е позади петите!!!
Не можеш да го продадеш алкохолот во оваа држава.
OK
Одитов во друга држава пак неможам да продадам 
Има решение некое ? . . .

**Comment by Pipelin** [comment]
Ако си купил во таа држава алкохол повторно тогаш неможеш. Мора да одиш во држава каде што ќе го продадеш алкохоло. Ама во таа држава да не купуваш повторно алкохол..

**Comment by JackDaniel** [comment]
фала многу  Pipelin
