### ISSUE TITLE
Не работи плакањето кауција во затвор

### ISSUE THREAD

**Issue by Janne123** [skechboy/MAFIA#74]
Кога си во затвор и да сакаш да си платеш кауција за тебе или некој друг неможе пишува 

ГРЕШКА!!!
Неможете да ја платета кауцијата за овој затвореник.
Затвореникот ќе биде наскоро ослободен поради доброто однесување. 

Мислам дека до мене е грешка или е ''bug'' незз пишете админи !

**Comment by hvardovski** [comment]
I kaj mene e isto

**Comment by hvardovski** [comment]
I kaj mene e isto

**Comment by npoptomov** [comment]
ne e ni greska ni bug ubavo ti pisuva naskoro ke bide osloboden t.e ako kaznata mu e pomalku od 1 min nemoze da se oslobodi t.e da se plati kaucija

**Comment by Pipelin** [comment]
Помалце од 2 мин неможеш да ослободиш.

**Comment by Janne123** [comment]
Okk ;) razbrav sea :O
