### ISSUE TITLE
Предлог за продавница

### ISSUE THREAD

**Issue by FilipTodorov** [skechboy/MAFIA#76]
Значи да не должам многу...
Да може и од оние од банка пари да си купуваме.. некако да се направи да си бираш
дали сакаш во Кеш или преку картичка (банка)

Подобро ке е ?

**Comment by pigmy** [comment]
Ne kje e... zashto nikoj nema da gi chuva parite vo kesh, kje gi chuva vo banka, a za da mu gi zemesh od banka treba da go ubiesh.. zatoa vaka e dobro

**Comment by Lart** [comment]
Се согласувам со Пигми

**Comment by kiprooo** [comment]
da i jas se soglasumva so lart i so pigmy char name Quick xD

**Comment by DroWRaNgeR** [comment]
da i jas se soglasuvam so kiprooo Lart i pigmy
xD

**Comment by barcellona** [comment]
jas se soglasuvam so lart pigmy kiprooo i drowranger   xD
