### ISSUE TITLE
Грешка во делот Алкохол

### ISSUE THREAD

**Issue by AsSass1N** [skechboy/MAFIA#77]
Во делот Алкохол---Продажба--- пишува дистотеки а треба "дискотеки"
еве слика http://img833.imageshack.us/img833/6104/greskamafia.jpg

**Comment by Pipelin** [comment]
Се работи за грешка во пишување, ќе го среди Skechboy тоа.

**Comment by AsSass1N** [comment]
Знам но сепак треба да се пријави.

**Comment by npoptomov** [comment]
smesni ste u seno barate igla

**Comment by Pipelin** [comment]
Ќе се поправи :)

**Comment by Grootix** [comment]
kade se prodava alkoxolot??

**Comment by JasSumToj** [comment]
haha kaj so imas droga pod nea..

**Comment by JasSumToj** [comment]
haha kaj so imas droga pod nea..

**Comment by lion4e** [comment]
alkoholot se prodava vo druga drzhava... pr. Italia go kupvash Makedonija go prodavash... :))) pozz

**Comment by skechboy** [comment]
Грешката е поправена ви благодарам за известувањето.
