### ISSUE TITLE
Zosto nemoze da se preprodava alkohol!

### ISSUE THREAD

**Issue by shadowrider1** [skechboy/MAFIA#78]
Jas sum nov no eve se imam preseleno 10 pati i sekogas mi vika policijata mi e zad peti koga sakam da preprodadam alkohol!!!

**Comment by shadowrider1** [comment]
sega koga se preseliv vo makedonija moze!!??

**Comment by Pipelin** [comment]
Оди во друга држава и таму продај го, откако ќе го продадеш купи алкохол и врати се во друга држава...и така...

**Comment by shadowrider1** [comment]
znam deka treba taka no vcera se preseliv 10 pati vo italija makedonija i sekogas vika greska policijata vi e zad petite i nakraj se vrativ vo makedonija i mi uspea!!!
