### ISSUE TITLE
Black Jack не работи

### ISSUE THREAD

**Issue by PrincessEmily** [skechboy/MAFIA#8]
Black Jack не работи воопшто, без разлика дали одам hit или stop се појавува ова
http://pic.mk/images/blackjack.

**Comment by skechboy** [comment]
Грешките во BlackJack-от се поправени. Доколку ви се појавува уште старата верзија од него освежете ја повеќе пати страницата и би требало се да е во ред. Ви благодарам за известувањето поздрав.

**Comment by blueman** [comment]
поправени се ама не е литературно напишано ако пишеме помала сума од 100 евра.. пишува сумата мора да БИДИ!?
