### ISSUE TITLE
Osloboduvanje

### ISSUE THREAD

**Issue by lion4e** [skechboy/MAFIA#80]
Mi ja plajka drug kaucijata i prati sho mi veli...

"Од:  suzuki  [Додади го на црната листа] [Пријави]
Дата:   17-12-10 23:29
До:   lion4e
Наслов:  
Кауцијата е платена
lion4e ја плати Вашата кауција од 11.700 € 

Сега сте слободен човек."

**Comment by kuche** [comment]
e dobro de te oslobodil. vrsel misija verojatno ... nema nisto greska ;)

**Comment by Cool4life** [comment]
:D

**Comment by Krichi** [comment]
a moze li sam da si ja platish kaucijata za sebe?

**Comment by kuche** [comment]
moze

**Comment by Lart** [comment]
Jas te oslobodiv togas, ja vrsev misijata oti nemozese jas da se oslobodam neznam oti

**Comment by Nexus123** [comment]
Децава како од марс да паднале -.-

**Comment by lion4e** [comment]
treba da imash kesh.... za sam da se oslobodish... :))
