### ISSUE TITLE
Нешто Во Врска Со Логирањето

### ISSUE THREAD

**Issue by DiChOoO** [skechboy/MAFIA#82]
Имам приметено кога се логирам го пишувам мојот јусернеим со мали букви и пишувам пасворд коректно и ми вика Грешка. После тоа кога се логирам го пишувам точно како што ми е јусернејмот односно со големи и мали букви и ми го прифаќа логирањето.. Ако можете направете без разлика како ќе го пишеме јусернејмот да може да се логира =)

**Comment by Pipelin** [comment]
Неможе да се направи. Значи осетливо е на голема или мала буква, тоа така и ќе остане.

**Comment by skechboy** [comment]
Мислам Pipelin даде убав одговор го затварам проблемот.
