### ISSUE TITLE
Унапредување 

### ISSUE THREAD

**Issue by darkob** [skechboy/MAFIA#83]
Мислам дека треба да се даваат некои награди кога ке се крене ранк :D

**Comment by Pipelin** [comment]
На какви награди мислиш? биди поконкретен?

Моќ, Пари, Платени убиства....?

**Comment by darkob** [comment]
па може пари , автомобили , дрога , алхохол .....
да не е вака ништо да немат :D

**Comment by darkob** [comment]
и ке имат нешто????
