### ISSUE TITLE
ПРОДАЖБА НА АВТОМОБИЛИ

### ISSUE THREAD

**Issue by hvardovski** [skechboy/MAFIA#84]
Да може украдените автомобили да се купуваат и продаваат меѓу играчите.ПОЗДРАВ!!!

**Comment by blueman** [comment]
добар предлог!...

**Comment by Cool4life** [comment]
Ми има текнато, добра идеја

**Comment by kiprooo** [comment]
dobar predlog

**Comment by Lart** [comment]
Се согласувам!

**Comment by ChillmaxTM** [comment]
Добар предлог. Бидејќи таа кола што не може да се украде некој играч да ти ја продаде. Добар предлог

**Comment by kiprooo** [comment]
a za koja cel ke sakam da ja kupam? nvm dobar predlog :) ah

**Comment by boge** [comment]
многу убав предлог

**Comment by gimen1001** [comment]
los predlog adminite ke izgubat vreme da go napraat toa a koj ke kupuva koli so ke mi e kola da kupam???
