### ISSUE TITLE
Za organiziran Kriminal

### ISSUE THREAD

**Issue by shadowrider1** [skechboy/MAFIA#85]
За организиран Криминал нели треба шоферот да купува кола!! Епа место да купува аавтомобил да украде еден!! Тоа е добро!

**Comment by hvardovski** [comment]
Grdo e toa.

**Comment by Cool4life** [comment]
Може, арно викаш

**Comment by shadowrider1** [comment]
sto e grdo!! sega ti trebaat 16.000 iljadi ti krades avtomobil go prodavas a posle go kupuvas istiot!!

**Comment by Lart** [comment]
Исти Курац
