### ISSUE TITLE
Кражба на Автомобили

### ISSUE THREAD

**Issue by NEWBOY** [skechboy/MAFIA#87]
Пишува таму дека кога ќе станеш ранг Џепчија ке можеш да крадеш, а доколку се обидеш се појавува ова:

ГРЕШКА!!!
Немаш доволно искуство да го украдеш избраниот автомобил!
OK

**Comment by Hellmafiamk** [comment]
Истото го има и за колите од Топ 5, јас сум Макро и истата грешка ми ја дава, а пишува од ранг Макро

**Comment by hvardovski** [comment]
И кај мене е исто,јас сум Џепџија и исто така ми вели.http://www.pic.mk/images/untitl1292697245.

**Comment by Lart** [comment]
Истото и кај мене, Џебџија сум и така ми вели, мака ми е за слика видете кај Кимса

**Comment by skechboy** [comment]
Ви благодарам за пријавувањето ќе испитаме што е проблемот поздрав

**Comment by DoooM** [comment]
Има и уште еден проблем...
Имам 100% шанса да украдам еден афтомобил и сепак понекогаш не успевам или пак одам во затвор...
Ако може да се поправи тогаш супер

**Comment by LjubeGVG** [comment]
i kaj mene isto

**Comment by skechboy** [comment]
Значи како што можете да приметете таму е јасно напишано:

Можеш да извршуваш поголеми кражби ПОСЛЕ ранг: Џепчија

што значи за да крадете подобри автомобили мора да имате ранг Крадец и соодветно Гангстер :)

**Comment by LjubeGVG** [comment]
denes dignav kradec i mi dave i eden predlog da gi dave da kradis avtomobili samo tie aso mozes a koga dignav gangster mi gi otvori a nemozev da gi kradam

**Comment by LjubeGVG** [comment]
i za rabota pisuvase ПОСЛЕ ранг: Џепчија pa koga bev Џепчија mozev da vrsam visoko plateni
