### ISSUE TITLE
Trkaloto

### ISSUE THREAD

**Issue by mkdstefan** [skechboy/MAFIA#88]
ja samo so sedna na kom i sakam da zavrtam trkaloto ... ne mi dava veke sum go vrtel vika.. a ja samo so sedna :@ :@ :@

**Comment by dare32** [comment]
da i na mene istoto mi se desi vcera go svrtiv i denes mi vika veke go imate svtreno .. .:@:@ wtf ?

**Comment by Manasijev** [comment]
Бидејќи после 24 можете пак да вртете .

**Comment by dare32** [comment]
sakas da kazis sekoj den po ednas ?

**Comment by kuche** [comment]
:@ restartirajte trkaloto... ne sum svrtil deneska ich ... a pokazuva deka e svrtenno:@ od v4era

**Comment by dare32** [comment]
ma za vcera i kaj mene bese istoto taka mi pokazvase :@:@

**Comment by dare32** [comment]
ma za vcera i kaj mene bese istoto taka mi pokazvase :@:@

**Comment by NEWBOY** [comment]
Ако го свртеш тркалото денеска на пример во 16:00 часот другиот ден ќе можеш пак да го свртеш но после 16:00 бидејќи пред 16 часот нема да има изминато 24 часа :)
