### ISSUE TITLE
edna golema greska[nevozmozno]

### ISSUE THREAD

**Issue by ToseTodorov** [skechboy/MAFIA#89]
mislam deka ova e golema greska  7 lvl cistac ? ? ? ? ? ?  ? 
#1  Граѓанин
#2  Поттрчко
#3  Џепчија
#4  Крадец
#5  Макро
#6  Гангстер
#7  Чистач ? ? ? ? ? ?
#8  Убиец
#9  Лидер
#10 Кум

**Comment by ToseTodorov** [comment]
ne e mozno ova

**Comment by ToseTodorov** [comment]
eeeej procita li nekoj

**Comment by barcellona** [comment]
graganin
pottrcko
dzepcija
cistac
kradec
makro
gangster
ubiec
lider
kum
mislam vaka bi bilo podobro
