### ISSUE TITLE
Лечење во болницата

### ISSUE THREAD

**Issue by PrincessEmily** [skechboy/MAFIA#9]
Не знам дали е ова проблем, но во претходната верзија кога здравјето е на 100% тогаш во болницата не е достапно лечење, а тука се појавува 
http://pic.mk/images/lecenje. ова го забележав, меѓутоа не знам дали е намерно направено вака да се појавува...

**Comment by skechboy** [comment]
Ти благорарам на известувањето. Сепак со промените во болницата тоа е направено намерно така поради тоа што како што видовте има опција за колку проценти да се излечите.

**Comment by PrincessEmily** [comment]
Во ред, извинете, не знаев затоа пријавив...

**Comment by skechboy** [comment]
Хахах нема потреба од извинување :) Твојата забелешка си беше на место.
