### ISSUE TITLE
Предлог за подароци

### ISSUE THREAD

**Issue by DiChOoO** [skechboy/MAFIA#90]
На пример да направите да може да се праќаат некој подароци помеѓу мафијашите.. Пример поени за напад, коли, мотори..

**Comment by Hellmafiamk** [comment]
ова не ти е MafiaWars

**Comment by JasSumToj** [comment]
Predlogot e dobar..na pr. eden igrac  da moze da praka pari,mok..na pr.koga ke vlezis na nekoj profil da ima :
Прати моќ на играчот,
Прати пари на играчот.
So toa bi mu pomognale na nekoj vas prijatel ili pak nekoj moze za vistinski pari da kupi mok od drug igrac.

**Comment by kikec2000** [comment]
da ama so toa ke ima mnogu hakovi!

**Comment by DiChOoO** [comment]
За тоа се тука админите.. Денеска приметив 1000 профили се избришани.. Некој многу се занесува и прави многу профили и после тоа бил многу добар во почит или во убиства.. Не се фер.. А за хакови ако има, бан одма!

**Comment by Lart** [comment]
Сакаш така? Оди на Мафиа Ворс

**Comment by Pipelin** [comment]
Предлогот не би се прифатил, според мене ќе се прават многу далавери. Кога ќе се направи фамилија сите играчи ќе му даваат пари на основачот за да се издигне, а тоа би било многу лошо и неферски нели е така?
Општо кажано, дали се работи за пари или нешто со што може исто така да се дојде до пари според мене е неприфатливо...

**Comment by kikec2000** [comment]
tocno!

**Comment by DiChOoO** [comment]
Vo pravo si ;)
