### ISSUE TITLE
Проблем со почит

### ISSUE THREAD

**Issue by kiprooo** [skechboy/MAFIA#91]
Ми пратија два поени за почит а на профилот тие ги нема, како да нема пратено никој [IMG]http://awesomescreenshot.com/0d24uvm72[/IMG]

**Comment by skechboy** [comment]
Највероватно те измамиле. Кога некој ќе ти прати почит пораките се во Системски пораки и бојата на насловот на пораката е различна.

**Comment by Lart** [comment]
Во светот на Мафијата постои и Измама.
