### ISSUE TITLE
Некој предлози за мафиа.мк 

### ISSUE THREAD

**Issue by JackDaniel** [skechboy/MAFIA#93]
Сум играл повеќе игри како мафиа.мк, но не ме задоволува во целост, пр. Torn City која ја играат 40.000 активно дневно играчи за разлика од мафиа.мк 300 дневно активни играчи зошто ?
Имам некој предлози за мафиа.мк кој ќе ви дадат некоја инспирација за следната сезона на мафиа.мк.
1.Да се разменуваат играчите со пари оружја и други работи , пазар да има кој што сите ќе ставаме цени во него и ќе купуваме појака марка на оружја и други работи . . .
2.Дрогата и Алкохолот не само да се продаваат туку и дa се употребуваат кој ќе имаат некаква намена пример : дрога употребуваш и ти дава 100 - 120 енергија зависи до дрогата . Кога ќе употребиш некаква дрога да ти се појави горе над Енергијата
2.Во продавниците да се продаваат оружја кој ќе ги употребуваш во напад пример : со нож , со раце , со боксирач напаѓаш и гледаш колку сила си му одземал на противникот..
3.Да купуваш Куќи , Базени , Палати скапи во кој ќе живееш а од Диско клубови Барови ако се твој добиваш дневна плата , употребуваш различни видови на цигари , со различни Одела го дотеруваш човекот .
4.Да имаш сопствена фирма за нелегални работи во која ќе вработуваш играчи и ќе земаат  дневна плата , можеш да работиш државно пример во амбуланта во која можеш да крадеш лекови за Енергија  и.т.н
5.Ако си во затвор можеш да побегнеш а ако те фатат ти одземаат енергија и ти го зголемуваат времето на чекање  пример и.т.н
6.Да направите некој добри работи кој што ќе ги купуваме со вистински пари Мастер Дајнерс или преку Порака и.т.н пример за побрзо да извршуваш Злосторства и.т.н
7.Секоја недела да има Мисии кој ти даваат различни работи 
8.Во фамилиите да има посебен Chat во кој што ќе се договараме , нападите на другите фамилии ќе траат повеќе време а и можеш да загинеш ...
9.Теретана во која ќе вежбаме и ќе јачаме моќ пример: појачуваш  Defense за одбрана и.т.н
10.Некои работи кој ќе ти служат компјутер во кој ќе ја хакираш страната на МВР, да направиш вируси и да го испратиш кај другите играчи и други работи ... - Да има Honor дека многу си убивал , многу си употребувал дрога , Патувал  и.т.н  (во Казиното ставете  _Покер_ да играме со другите играчи) 
Има уште многу работи кој ќе го подобри квалитетот во играта 

Поздрав JackDaniel

**Comment by DiChOoO** [comment]
Добар предлог пријателе :)

**Comment by kiprooo** [comment]
супер идеа. Браво. Се надевам дека модераторите ќе ги следат овие предлози :)

**Comment by skechboy** [comment]
Навистина многу конструктивни предлози. Ќе гледаме во блиска иднина да реализираме неколку од овие предлози.

**Comment by Lart** [comment]
Се согласувам со сите предлози, најмногу со Теретана, најреално е Теретана да има!

**Comment by kiprooo** [comment]
Ако нека се исполнат овие услови, но и вака Мафиа.мк е најдобра!!!:)

**Comment by ChillmaxTM** [comment]
Добар предлог. Но некој нека ми одговори за предлог на дрогата, и да ми кажете што мислите за предлогот.
Поздрав, од igorbest
