### ISSUE TITLE
Имам едно мислење кое може да послужи.....

### ISSUE THREAD

**Issue by DonNicky** [skechboy/MAFIA#98]
Кога ке ги отвориме активните мафијаши ... до секој мафијаш има опција да му кликнеме на тајниот линк... епа вака да е со друга боја знакот за тајниот линк на оние што сме им кликнале или што ни имаат кликнато на тајниот линк ... така по прегледно ке имаме кој ни е кликнал на линкот.... за да не губиме време да кликнуваме на секој ... поздрав

**Comment by skechboy** [comment]
Предлогот ти е на место но за жал моменталните технички услови не ни го дозволуваат да го реализираме.
